/* ====== Health Reversal Plan — bilingual data ====== */
window.HC_DATA = {
  // Hero
  hero: {
    eyebrow: { en: "6-Month Health Reversal Plan · March 2026 Edition", zh: "6 個月健康逆轉計畫 · 2026 年 3 月個人化版" },
    title:   { en: ["Normalize four markers,", "from the ", "ground up."],
               zh: ["從根基修復", "同步正常化", "四項關鍵指標"] },
    titleEm: { en: "without medication first", zh: "先以生活方式介入" },
    lede:    { en: "Sleep, BP, lipids, uric acid — one shared metabolic root. Lifestyle stacks first; medication only after lifestyle plateaus.",
               zh: "睡眠、血壓、血脂、尿酸——共享同一個代謝根源。生活方式介入優先，等到效果平台期再考慮藥物。" },
    progressLbl: { en: "Weight progress · 70 → 65 kg", zh: "體重進度 · 70 → 65 公斤" },
    progressMeta: { en: "Day 49 · 67.8 kg · Sat official (5/2)", zh: "第 49 天 · 67.8 公斤 · 週六正式（5/2）" },
    startDate: { en: "Start date · Mar 17, 2026 · Last sync 5/4", zh: "起始日期 · 2026 年 3 月 17 日 · 最後同步 5/4" },
    startWeight: 70,
    targetWeight: 65,
    currentWeight: 67.8,
    currentWeightDate: "5/2 Sat official",
  },

  markers: [
    {
      sys: "heart", name: { en: "Blood Pressure", zh: "血壓" },
      val: "124/72", unit: "mmHg",
      delta: { en: "W18 weekly avg (4 days) · target met (<130) · last 113/68 (5/3)", zh: "W18 週均（4 天）· 已達標 (<130) · 最新 113/68 (5/3)" },
      cadence: { en: "Daily · weekly avg", zh: "每日 · 週均" },
      status: "ok",
    },
    {
      sys: "sleep", name: { en: "Sleep Score", zh: "睡眠分數" },
      val: "77", unit: "Garmin",
      delta: { en: "5/4 · OSA flag: T90 18.4% (severe)", zh: "5/4 · OSA 紅旗：T90 18.4%（重度）" },
      cadence: { en: "Daily · Garmin", zh: "每日 · Garmin" },
      status: "warn",
    },
    {
      sys: "weight", name: { en: "Weight", zh: "體重" },
      val: "67.8", unit: "kg",
      delta: { en: "5/2 Sat official · auto-synced", zh: "5/2 週六正式 · 自動同步" },
      cadence: { en: "Daily · Sat official", zh: "每日 · 週六正式" },
      status: "ok",
    },
    {
      sys: "uric", name: { en: "Uric Acid", zh: "尿酸" },
      val: "8.9", unit: "mg/dL",
      delta: { en: "Constitutional · neph. referral", zh: "體質性偏高 · 已轉診腎臟科" },
      cadence: { en: "Lab only · last Mar 25", zh: "僅實驗室 · 上次 3/25" },
      status: "bad",
    },
  ],

  tabs: [
    { id: "overview", en: "Overview", zh: "總覽" },
    { id: "sleep",    en: "Sleep",    zh: "睡眠" },
    { id: "diet",     en: "Diet",     zh: "飲食" },
    { id: "exercise", en: "Wall sits", zh: "靠牆深蹲" },
    { id: "running",  en: "Running",  zh: "跑步" },
    { id: "supps",    en: "Supplements", zh: "保健品" },
    { id: "routine",  en: "Daily Routine", zh: "每日作息" },
    { id: "timeline", en: "Timeline", zh: "時程" },
    { id: "safety",   en: "Safety",   zh: "安全" },
    { id: "dashboard",en: "Dashboard",zh: "儀表板" },
    { id: "tracker",  en: "Tracker",  zh: "追蹤" },
  ],

  // ===== Dashboard (auto-generated PNG) =====
  dashboard: {
    ttl: { en: "Health Dashboard", zh: "健康儀表板" },
    sub: { en: "Trend charts: weight, body composition, BP / heart rate, Sleep Score. Auto-generated from reviews/daily/*.md after each check-in by scripts/generate_dashboard.py.",
           zh: "趨勢圖：體重、體組成、血壓 / 心率、Sleep Score。每次 daily check-in 後由 scripts/generate_dashboard.py 從 reviews/daily/*.md 自動生成。" },
    src: "reviews/health_dashboard.png",
    fallback: "https://raw.githubusercontent.com/Eaglemamba/Health-Check/main/reviews/health_dashboard.png",
    spo2Src: "reviews/daily/spo2/spo2_desat_trend.png",
    spo2Fallback: "https://raw.githubusercontent.com/Eaglemamba/Health-Check/main/reviews/daily/spo2/spo2_desat_trend.png",
  },

  // ===== Overview =====
  overview: {
    profile: {
      en: [
        ["ECG LVH", "11-yr chronic (since 2015 age 26) · 2026-03-25 added biatrial enlargement + anterior ST↑ · echo + 24h Holter pending"],
        ["Bedtime", "22:00–22:40 (target 22:30)"],
        ["Actual sleep", "6.0–7.2 h · W17 avg Sleep Score 71.4"],
        ["Garmin (W17)", "Body Battery 56.7 · RHR 56–61"],
        ["BP (W18 avg)", "124/72 mmHg · meets <130 general · LVH-target <125/75 borderline"],
        ["Weight (5/2 Sat)", "67.8 kg · 20.2% BF · VFL 9.5"],
        ["OSA flag", "T90 18.4% on 5/4 · POSA trial 5/5–5/8 · driving LVH/biatrial progression"],
        ["Running", "Started 4/26 — building base"],
        ["Current supps", "Omega-3 4g, hibiscus, D3K2, cherry, Mg, citrulline, psyllium 10g"],
        ["Discontinued", "NOW EGCG (AST 27→38, stopped 4/21)"],
      ],
      zh: [
        ["ECG LVH", "11 年慢性（2015 age 26 起）· 2026-03-25 新增雙心房擴大 + 前壁 ST↑ · 心臟超音波 + 24h Holter 待安排"],
        ["就寢時間", "22:00–22:40（目標 22:30）"],
        ["實際睡眠", "6.0–7.2 小時 · W17 平均 Sleep Score 71.4"],
        ["Garmin（W17）", "身體電量 56.7 · RHR 56–61"],
        ["血壓（W18 週均）", "124/72 mmHg · 一般 <130 達標 · LVH 目標 <125/75 仍邊緣"],
        ["體重（5/2 週六）", "67.8 公斤 · 體脂 20.2% · 內臟 9.5"],
        ["OSA 紅旗", "5/4 T90 18.4% · 體位治療試驗 5/5–5/8 · 持續推進 LVH / 雙心房擴大"],
        ["跑步", "4/26 開始，建立基礎中"],
        ["目前保健品", "Omega-3 4g、洛神花、D3K2、酸櫻桃、鎂、瓜胺酸、洋車前子 10g"],
        ["已停用", "NOW EGCG（AST 27→38，4/21 停用）"],
      ],
    },
    priority: {
      title: { en: "Top priority — fix sleep first", zh: "最高優先 — 先修復睡眠" },
      body: {
        en: "5–6 h of actual sleep + Body Battery 40–50 means sleep deprivation is undermining metabolic repair from the ground up. Without sleep, even a perfect diet and exercise regimen delivers only 50% of its potential.",
        zh: "實際睡眠 5–6 小時 + 身體電量 40–50，代表睡眠不足正在從根基破壞所有代謝修復。如果不先修好睡眠，即使完美的飲食和運動計畫也只能發揮 50% 的效果。",
      },
      order: {
        en: ["Sleep repair + OSA screening", "Shift hydration earlier", "Wall sits", "Diet adjustments", "Supplements"],
        zh: ["睡眠修復 + OSA 篩檢", "提前補水時間", "靠牆深蹲", "飲食調整", "保健品"],
      },
    },
    stack: {
      title: { en: "BP-lowering combination — interventions stack", zh: "降壓組合 — 介入效果疊加" },
      sub:   { en: "Each row layers on top of the others. Diastolic is already 75 — lifestyle first prevents over-dipping.",
               zh: "以下每項介入效果可以疊加。舒張壓已經 75，生活方式優先以避免過度下降。" },
      head:  { en: ["Intervention", "SBP reduction", "Notes"],
               zh: ["介入措施", "收縮壓降幅", "備註"] },
      rows: [
        ["wallsit", { en: "Wall sits 3×/week", zh: "靠牆深蹲 3次/週" }, "−10 to −13 mmHg",
          { en: "Visible at 12 weeks; equivalent to one BP medication", zh: "12 週可見效；等同一種降壓藥" }],
        ["sodium",  { en: "Sodium < 1,500 mg/day", zh: "鈉攝取 < 1,500 mg/天" }, "−5 to −8 mmHg",
          { en: "Sodium impacts systolic more than diastolic", zh: "鈉對收縮壓影響大於舒張壓" }],
        ["omega",   { en: "Omega-3 ~2 g/day", zh: "Omega-3 ~2 g/天" }, "−4 to −5 mmHg",
          { en: "Preferentially lowers systolic", zh: "優先降低收縮壓" }],
        ["sleep",   { en: "Sleep repair to 7+ hours", zh: "睡眠修復至 7+ 小時" }, "−3 to −5 mmHg",
          { en: "Reduces sympathetic overactivation", zh: "降低交感神經過度活化" }],
        ["weight",  { en: "Weight loss of 5 kg", zh: "減重 5 公斤" }, "−3 to −5 mmHg",
          { en: "~1 mmHg per kg lost", zh: "每減 1 kg 約降 1 mmHg" }],
        ["combo",   { en: "Combined potential", zh: "合併效果" }, "−25 to −36 mmHg",
          { en: "135 → 99–110 range", zh: "135 → 99–110 範圍" }],
      ],
    },
  },

  // ===== Sleep =====
  sleep: {
    intro: {
      en: "Lies down 20:30 → wakes 2–4 AM for nocturia → alert after bathroom → starts working → actual sleep 5–6 h. Goal: delay nocturia to 5:00–5:30, achieve 8.5–9 h.",
      zh: "20:30 躺下 → 凌晨 2–4 點夜尿醒來 → 上完廁所精神清醒 → 起床工作 → 實際睡眠 5–6 小時。目標：將夜尿延後至 5:00–5:30，達成 8.5–9 小時睡眠。",
    },
    pillars: [
      {
        ttl: { en: "A. Solve nocturia (upstream)", zh: "A. 解決夜尿（上游問題）" },
        items: {
          en: [
            "Reduce fluids after 17:00; minimal soup at dinner.",
            "Pre-bed leg elevation 15–20 min at 20:00 — fluid returns to circulation, kidneys process before sleep.",
            "Always urinate at 20:00 even without urge.",
            "After 18:30, lip-moistening sips only.",
          ],
          zh: [
            "17:00 後減少液體攝取，晚餐少喝湯。",
            "20:00 睡前抬腿 15–20 分鐘 — 下肢液體回流，腎臟入睡前處理。",
            "20:00 一定要上廁所，即使沒有尿意。",
            "18:30 後僅「潤唇式」小啜。",
          ],
        },
      },
      {
        ttl: { en: "B. If you wake, force return to sleep", zh: "B. 半夜醒來，強迫回去睡" },
        items: {
          en: [
            "Lights off; dim warm nightlight only. No phone, no clock.",
            "Return to bed immediately. 4-7-8 breathing × 2–3 cycles.",
            "Hard rule: do not leave bed before 5:30 AM.",
            "Quiet rest still gives ~50% of deep sleep recovery.",
          ],
          zh: [
            "全程不開燈，僅暖色低亮夜燈。不碰手機、不看時鐘。",
            "立即回床。4-7-8 呼吸法 × 2–3 個循環。",
            "硬規則：5:30 之前不離床。",
            "安靜休息仍可提供深度睡眠約 50% 的恢復效果。",
          ],
        },
      },
      {
        ttl: { en: "C. OSA screening", zh: "C. OSA 篩檢" },
        items: {
          en: [
            "Enable Garmin Pulse Ox tonight — observe 5–7 nights for SpO2 < 90%.",
            "Phone audio recording overnight for snoring / apnea.",
            "Book sleep clinic (pulmonology / ENT) + urology for nocturia.",
            "Bring Sleep Score, Body Battery, Pulse Ox data to doctor.",
          ],
          zh: [
            "今晚開啟 Garmin Pulse Ox — 觀察 5–7 晚 SpO2 是否 < 90%。",
            "手機錄音 app 整夜錄音檢查打鼾／呼吸暫停。",
            "預約睡眠門診（胸腔／耳鼻喉）+ 泌尿科夜尿評估。",
            "帶 Sleep Score、Body Battery、Pulse Ox 數據給醫師。",
          ],
        },
      },
      {
        ttl: { en: "D. Sleep position", zh: "D. 睡姿" },
        items: {
          en: [
            "Side sleep (left preferred) — supine collapses tongue base, ~50% more apnea.",
            "Pillow behind back to prevent rolling supine.",
            "Elevate head 15–20° — reduces airway pressure & reflux.",
          ],
          zh: [
            "側睡（左側為佳）— 仰睡使舌根後墜，呼吸暫停多 ~50%。",
            "背後放枕頭防止翻回仰躺。",
            "墊高床頭 15–20° — 減少呼吸道壓力與胃食道逆流。",
          ],
        },
      },
    ],
    cbti: {
      ttl: { en: "CBT-I — first-line, ranked by impact", zh: "CBT-I — 第一線療法，依證據強度排序" },
      head: { en: ["#", "Intervention", "Mechanism", "Your application"],
              zh: ["#", "介入", "機轉", "你的應用"] },
      rows: [
        ["1", { en: "Sleep restriction", zh: "睡眠限制" },
               { en: "Build adenosine pressure by limiting time in bed", zh: "限制躺床時間以建立腺苷壓力" },
               { en: "No bed before 20:00; no bed past 5:30", zh: "20:00 前不躺床；5:30 後不躺床" }],
        ["2", { en: "Stimulus control", zh: "刺激控制" },
               { en: "Bed = sleep only", zh: "床 = 只用來睡覺" },
               { en: "If awake >20 min, get up — no screens", zh: "醒著 >20 分鐘就起床，不碰螢幕" }],
        ["3", { en: "Sleep hygiene", zh: "睡眠衛生" },
               { en: "Environment & behavior", zh: "環境與行為" },
               { en: "Blackout, 18–20°C, no caffeine after 14:00", zh: "全黑、18–20°C、14:00 後無咖啡因" }],
        ["4", { en: "Relaxation", zh: "放鬆技巧" },
               { en: "Reduce pre-sleep arousal", zh: "降低入睡前覺醒" },
               { en: "4-7-8 breathing, leg elevation", zh: "4-7-8 呼吸法、抬腿" }],
        ["5", { en: "Cognitive restructuring", zh: "認知重建" },
               { en: "Reduce performance anxiety", zh: "降低對睡眠的焦慮" },
               { en: "“Quiet rest is 50% of deep sleep”", zh: "「安靜休息有深度睡眠 50% 效果」" }],
      ],
    },
    metrics: {
      ttl: { en: "Tracking metrics", zh: "追蹤指標" },
      items: [
        ["Sleep Score", "≥ 70 → 80", "var(--sleep)"],
        ["Body Battery (waking)", "≥ 65 → 75", "var(--metabolic)"],
        ["Deep sleep %", "> 15%", "var(--uric)"],
        ["Pulse Ox SpO2", "stable, no dips < 90%", "var(--water)"],
      ],
    },
  },

  // ===== Diet =====
  diet: {
    macros: [
      ["calories",  { en: "Calories", zh: "熱量" }, "1,950–2,050", "kcal", { en: "Base · +150 on training days", zh: "基礎 · 運動日 +150" }],
      ["protein",   { en: "Protein", zh: "蛋白質" }, "95", "g", { en: "Range 85–115 · ~30 g/meal", zh: "區間 85–115 · 每餐 ~30g" }],
      ["fat",       { en: "Fat", zh: "脂肪" }, "55–60", "g", { en: "Hard floor 50 · MUFA-led", zh: "硬下限 50 · 以單元不飽和為主" }],
      ["carbs",     { en: "Carbs", zh: "碳水" }, "170–200", "g", { en: "Complex, low-GI", zh: "複合、低 GI" }],
      ["sodium",    { en: "Sodium", zh: "鈉" }, "< 1,500", "mg", { en: "Hard cap 2,000", zh: "硬上限 2,000" }],
      ["fiber",     { en: "Fiber", zh: "纖維" }, "28–32", "g", { en: "β-glucan 3 g/day", zh: "β-glucan 3 g/天" }],
      ["water",     { en: "Water", zh: "飲水" }, "2.5–3.0", "L", { en: "Done by 17:00", zh: "17:00 前完成" }],
    ],
    combos: [
      { name: { en: "DIY Assembly", zh: "DIY 組裝" }, recommended: true,
        desc: { en: "Steamed sweet potato + ready-to-eat chicken breast + black soy milk. Add a tea egg.",
                zh: "蒸地瓜 + 即食雞胸肉 + 黑豆漿 + 茶葉蛋。" },
        kcal: 450, sodium: 410, protein: 32 },
      { name: { en: "Grilled Chicken Box", zh: "香烤雞胸便當" },
        desc: { en: "7-11 Simple Fit. Purple rice, broccoli, carrot, king oyster mushroom.",
                zh: "7-11 Simple Fit 香烤雞胸鮮蔬餐。紫米、花椰菜、紅蘿蔔、杏鮑菇。" },
        kcal: 374, sodium: 577, protein: 18 },
      { name: { en: "Cauliflower Low-Carb", zh: "減醣花椰菜飯" },
        desc: { en: "Chicken breast cauliflower rice. Triglyceride-friendly.",
                zh: "雞胸花椰菜飯減醣餐。對三酸甘油酯友善。" },
        kcal: 319, sodium: 600, protein: 20 },
      { name: { en: "Sweet Potato Premium", zh: "地瓜經典升級" },
        desc: { en: "Sweet potato + sous vide chicken + edamame + black soy milk.",
                zh: "蒸地瓜 + 舒肥雞胸 + 鹽味毛豆 + 黑豆漿。" },
        kcal: 470, sodium: 725, protein: 35 },
      { name: { en: "Oatmeal + Chicken", zh: "燕麥 + 雞胸" },
        desc: { en: "50–60 g oats brewed with milk + chicken breast + tea egg. β-glucan 3 g hits LDL target.",
                zh: "50–60 g 燕麥沖牛奶 + 雞胸 + 茶葉蛋。β-glucan 3 g 達到降 LDL 目標。" },
        kcal: 470, sodium: 500, protein: 28 },
      { name: { en: "Sweet Potato + Egg Salad", zh: "地瓜 + 蛋沙拉" },
        desc: { en: "Sweet potato + 2 tea eggs + Simple-Fit salad (½ dressing) + grain soy milk.",
                zh: "地瓜 + 茶葉蛋 ×2 + 繽紛蔬菜沙拉（醬料一半）+ 健康穀物豆漿。" },
        kcal: 530, sodium: 700, protein: 26 },
    ],
    avoid: {
      en: ["Sugary drinks", "Beer", "Organ meats", "Processed meats", "Fried foods", "Instant noodles", "Shellfish", "Excessive white rice", "Bubble tea", "Pig blood cake"],
      zh: ["含糖飲料", "啤酒", "內臟", "加工肉品", "油炸食品", "泡麵", "蝦蟹貝類", "過量白飯", "珍珠奶茶", "豬血糕"],
    },
    increase: {
      en: ["Low-fat dairy", "Oats", "Edamame / tofu", "Unsalted nuts 15g", "Cherries / blueberries", "Sweet potato", "Black fungus", "Green / oolong tea", "Guava", "Kiwi"],
      zh: ["低脂乳製品", "燕麥", "毛豆 / 豆腐", "無調味堅果 15g", "櫻桃 / 藍莓", "地瓜", "黑木耳", "綠茶 / 烏龍茶", "芭樂", "奇異果"],
    },
    fructose: {
      ttl: { en: "Bubble tea — sugar reality check", zh: "珍珠奶茶 — 含糖真相" },
      sub: { en: "Fructose → KHK (no feedback inhibition) → ATP depletion → AMP → IMP → uric acid. One full-sugar bubble tea hits UA harder than a plate of shrimp.",
             zh: "果糖 → KHK（無回饋抑制）→ ATP 耗竭 → AMP → IMP → 尿酸。一杯全糖珍奶對尿酸的衝擊大於一盤蝦。" },
      rows: [
        [{ en: "Minimal (一分糖)", zh: "一分糖" }, "10g", "2"],
        [{ en: "Less sweet (微糖)", zh: "微糖" }, "15–25g", "3–5"],
        [{ en: "Half sweet (半糖)", zh: "半糖" }, "30–35g", "6–7"],
        [{ en: "Full sweet (全糖)", zh: "全糖" }, "50–52.5g", "10 — full WHO daily limit"],
      ],
    },
    breakfast: {
      ttl: { en: "Breakfast — 5 rotations (target 350–400 kcal)", zh: "早餐 — 5 輪替（目標 350–400 kcal）" },
      sub: { en: "One daily hot latte option: low-fat milk ~120–150 kcal. Casein promotes UA excretion; chlorogenic acid associated with reduced gout risk. Best 9–10 AM after 300–400 mL warm water.",
             zh: "每日一杯熱拿鐵：低脂奶 ~120–150 kcal。酪蛋白促進尿酸排泄；綠原酸與降低痛風風險相關。最佳 9–10 點，先喝 300–400 mL 溫水。" },
      head: { en: ["Rotation", "Items", "~kcal", "Highlight"],
              zh: ["輪替", "品項", "約熱量", "亮點"] },
      rows: [
        [{ en: "A: Sweet Potato Classic", zh: "A：地瓜經典" },
          { en: "Baked sweet potato + tea egg + unsweetened soy milk", zh: "烤地瓜 + 茶葉蛋 + 無糖豆漿" },
          "~350", { en: "Low GI + low-purine protein", zh: "低 GI + 低普林蛋白" }],
        [{ en: "B: Improved Sandwich", zh: "B：改良三明治" },
          { en: "Grilled chicken veggie sandwich (light sauce) + unsweetened soy milk", zh: "烤雞蔬菜三明治（少醬）+ 無糖豆漿" },
          "~360", { en: "Grilled chicken replaces fried egg", zh: "烤雞取代煎蛋" }],
        [{ en: "C: Latte Day", zh: "C：拿鐵日" },
          { en: "Tea eggs ×3 + low-fat hot latte", zh: "茶葉蛋 ×3 + 低脂熱拿鐵" },
          "~440", { en: "3 eggs ≈ 19.5g protein crosses 2.5–3g leucine threshold", zh: "3 顆蛋 ≈ 19.5g 蛋白跨 leucine 門檻" }],
        [{ en: "D: High Fiber", zh: "D：高纖" },
          { en: "Unsweetened Greek yogurt + banana + small nut pack", zh: "無糖希臘優格 + 香蕉 + 小包堅果" },
          "~380", { en: "β-glucan lowers LDL", zh: "β-glucan 降 LDL" }],
        [{ en: "E: Oatmeal Power", zh: "E：燕麥力量" },
          { en: "Oats 40g + boiled egg + unsweetened soy milk 300ml + nuts 10g", zh: "桂格燕麥片 40g + 水煮蛋 + 無糖豆漿 300ml + 堅果 10g" },
          "~390", { en: "β-glucan 3g lowers LDL 5–10%", zh: "β-glucan 3g 降 LDL 5–10%" }],
      ],
      oatTips: {
        ttl: { en: "Oatmeal tips (桂格機能燕麥片)", zh: "燕麥早餐要訣（桂格機能燕麥片）" },
        items: {
          en: [
            "Serving: 40–50g dry (~150–180 kcal). Brew with hot water or unsweetened soy milk; no sugar — pinch of cinnamon for flavor.",
            "Must pair with protein (egg, soy milk, Greek yogurt) — oats alone still cause moderate glucose spike.",
            "β-glucan needs water to work — drink ≥300 mL alongside.",
            "Functional series with added flavor packets can exceed 200 mg sodium/serving — check label.",
          ],
          zh: [
            "份量：乾燥 40–50g（~150–180 kcal）。熱水或無糖豆漿沖泡；不加糖，少許肉桂調味。",
            "必須搭配蛋白質（蛋、豆漿、希臘優格）— 單吃燕麥仍會造成中等血糖波動。",
            "β-glucan 需足夠水分 — 搭配 ≥300 mL 飲品。",
            "機能系列調味包可能超過 200 mg 鈉/份 — 看標示。",
          ],
        },
      },
    },
    yogurtBlend: {
      ttl: { en: "Breakfast yogurt drink — complete recipe (2026-04-21)", zh: "早餐優格飲 — 完整配方（2026-04-21）" },
      head: { en: ["Ingredient", "Amount", "Provides"],
              zh: ["材料", "份量", "提供"] },
      rows: [
        [{ en: "Unsweetened yogurt (store-bought)", zh: "無糖優格（市售）" }, "~200g",
          { en: "Probiotics + calcium + low-impact lactose", zh: "益生菌 + 鈣 + 低衝擊乳糖" }],
        [{ en: "Whey protein", zh: "乳清蛋白" }, "30g (1 scoop)",
          { en: "25–30g protein + leucine for MPS", zh: "25–30g 蛋白 + leucine 啟動 MPS" }],
        [{ en: "Mixed nuts", zh: "綜合堅果" }, "~30g",
          { en: "MUFA + Mg + fat-soluble vit carrier", zh: "MUFA + 鎂 + 脂溶性維他命載體" }],
        [{ en: "Goji berries (whole)", zh: "枸杞（整顆打）" }, "15–20g",
          { en: "Polysaccharides + fiber + β-sitosterol intact (vs steeped tea)", zh: "多醣 + 纖維 + β-sitosterol（vs 沖泡只取水溶性）" }],
        [{ en: "Blueberries", zh: "藍莓" }, "80–100g",
          { en: "Anthocyanins → hsCRP ↓ + LDL oxidation ↓", zh: "花青素 → hsCRP ↓ + LDL 氧化 ↓" }],
        [{ en: "Banana (optional)", zh: "香蕉（選填）" }, { en: "half, slightly green", zh: "半根，略青" },
          { en: "K+ → BP + resistant starch (HbA1c-friendly)", zh: "鉀 → BP + 抗性澱粉（HbA1c 友善）" }],
        [{ en: "Raw cacao powder (non-alkalized)", zh: "生可可粉（non-alkalized）" }, "5–10g",
          { en: "Flavanols → SBP −2–3 mmHg (Ried 2020 Cochrane). Must be non-alkalized.", zh: "Flavanols → SBP −2–3 mmHg（Ried 2020 Cochrane）。必須 non-alkalized。" }],
        [{ en: "L-Citrulline", zh: "L-瓜胺酸" }, "2g",
          { en: "NO precursor → BP adjunct (sub-RCT dose, additive)", zh: "NO 前體 → BP 輔助（低於 RCT 劑量，疊加效果）" }],
        [{ en: "D3 + K2", zh: "D3 + K2" }, "D3 2000 IU + K2 MK-7 100 mcg",
          { en: "Fat-soluble — yogurt+nuts fat enables absorption", zh: "脂溶性 — 優格+堅果脂肪助吸收" }],
        [{ en: "Matcha — REMOVED 2026-04-21", zh: "抹茶 — 2026-04-21 移除" }, "—",
          { en: "Moved to lunch latte (single dose). EGCG+protein binding wastes ~20–30% at breakfast.", zh: "改午餐拿鐵（單一劑量）。早餐 EGCG+蛋白結合浪費 ~20–30%。" }],
        [{ en: "Creatine — not currently added", zh: "肌酸 — 目前未加" }, "—",
          { en: "Pending RT resumption. Confounds weight + serum creatinine (eGFR misread).", zh: "待重訓恢復後加。會干擾體重 + 血清肌酸酐（eGFR 誤判）。" }],
      ],
      note: {
        en: "Probiotics already in store-bought yogurt — no separate capsule. Chia/walnuts can add omega-3 ALA.",
        zh: "市售優格已含益生菌 — 不需另加膠囊。可加奇亞籽 / 核桃補 omega-3 ALA。",
      },
      blending: {
        en: "Blending retains all fiber (only physical structure changes); juicing discards fiber. With protein and fat, fructose absorption slows further — not equivalent to juice.",
        zh: "果汁機保留所有纖維（僅物理結構改變）；榨汁則丟棄纖維。配蛋白質與脂肪，果糖吸收進一步減慢 — 不等同果汁。",
      },
    },
    boxes711: {
      ttl: { en: "7-11 main lunch boxes (Simple Fit preferred)", zh: "7-11 主力便當（Simple Fit 優先）" },
      sub: { en: "Consumer Foundation: 75% of convenience-store microwave meals exceed sodium limits. Always flip and check 鈉.",
             zh: "消基會調查：75% 超商微波便當鈉超標。一定要翻背面看「鈉」。" },
      head: { en: ["Item", "kcal", "Sodium", "Protein", "Notes"],
              zh: ["品項", "熱量", "鈉", "蛋白", "備註"] },
      rows: [
        [{ en: "香烤雞胸鮮蔬餐 (Grilled Chicken Veggie)", zh: "香烤雞胸鮮蔬餐" }, "~374", "~577mg", "~18.4g",
          { en: "Purple rice, broccoli, carrot, king oyster, boiled egg ~$89. BEST", zh: "紫米、花椰菜、紅蘿蔔、杏鮑菇、水煮蛋 ~$89。首選" },
          true],
        [{ en: "雞胸肉花椰菜飯減醣餐 (Cauliflower Rice Low-Carb)", zh: "雞胸肉花椰菜飯減醣餐" }, "~319", "~500–700mg", "~20g",
          { en: "Cauliflower rice replaces white rice — TG-friendly", zh: "花椰菜飯取代白飯 — TG 友善" }, false],
        [{ en: "豆酥烤魚鮮蔬便當 (Bean-Crusted Fish)", zh: "豆酥烤魚鮮蔬便當" }, "~437", "~600–800mg", "~18g",
          { en: "Purple rice, pan-fried fish, broccoli, edamame, sprouts", zh: "紫米、煎魚、花椰菜、毛豆、豆芽" }, false],
        [{ en: "繽紛鮮蔬烤雞便當 (Veggie Roast Chicken)", zh: "繽紛鮮蔬烤雞便當" }, "~370", "~550–700mg", "~18g",
          { en: "Purple rice, skinless roast chicken, mixed veg", zh: "紫米、去皮烤雞、多種蔬菜" }, false],
      ],
      avoid: {
        ttl: { en: "Boxes to avoid", zh: "避免的便當" },
        body: { en: "香草烤雞腿時蔬餐 — sodium ~987mg, exceeds limit. 增肌蛋白餐 — 595 kcal too high + sodium >900mg.",
                zh: "香草烤雞腿時蔬餐 — 鈉 ~987mg 超標。增肌蛋白餐 — 595 kcal 過高 + 鈉 >900mg。" },
      },
    },
    proteinSides: {
      ttl: { en: "Individual protein items & sides", zh: "單品蛋白質與配菜" },
      head: { en: ["Item", "kcal", "Sodium", "Protein", "Rating"],
              zh: ["品項", "熱量", "鈉", "蛋白", "評級"] },
      rows: [
        [{ en: "Ready-to-eat chicken breast (plain) 即食雞胸肉", zh: "即食雞胸肉（原味）" }, "~104–115", "~300–450mg", "~22–24g",
          { en: "Recommended", zh: "推薦" }, "ok"],
        [{ en: "Sous vide chicken 法式舒肥嫩雞胸", zh: "法式舒肥嫩雞胸" }, "~104", { en: "per label", zh: "依標示" }, "~22g",
          { en: "Recommended", zh: "推薦" }, "ok"],
        [{ en: "Tea egg 茶葉蛋", zh: "茶葉蛋" }, "~70–80", "~200–229mg", "~6.5g",
          { en: "OK (limit 1/meal)", zh: "可（每餐限 1）" }, "warn"],
        [{ en: "Steamed sweet potato 蒸地瓜 (~100–150g)", zh: "蒸地瓜（100–150g）" }, "~100–150", "~15–30mg", "~2g",
          { en: "Best carb — ultra-low Na, high K", zh: "最佳碳水 — 超低鈉、高鉀" }, "ok"],
        [{ en: "Salted edamame 鹽味毛豆", zh: "鹽味毛豆" }, "~97", "~315mg", "~7.9g",
          { en: "Best legume snack", zh: "最佳豆類點心" }, "ok"],
      ],
    },
    tofu: {
      ttl: { en: "Tofu products — sodium truth", zh: "豆腐製品 — 鈉含量真相" },
      head: { en: ["Item", "Sodium/100g", "Rating", "Notes"],
              zh: ["品項", "鈉/100g", "評級", "備註"] },
      rows: [
        [{ en: "板豆腐 Firm tofu (plain)", zh: "板豆腐（原味）" }, "~2mg", "ok",
          { en: "Near-zero Na, high Ca 140mg", zh: "幾乎零鈉，高鈣 140mg" }],
        [{ en: "嫩豆腐 Silken tofu (plain)", zh: "嫩豆腐（原味）" }, "~45mg", "ok",
          { en: "Low Na, low cal", zh: "低鈉、低卡" }],
        [{ en: "五香豆干 Five-spice dried tofu", zh: "五香豆干" }, "~445mg", "warn",
          { en: "Already high — control portions", zh: "底子已高 — 控制份量" }],
        [{ en: "涼拌豆腐 Cold tofu (with sauce)", zh: "涼拌豆腐（加醬）" }, "~350–650mg", "warn",
          { en: "Sauce packet is the variable — use half", zh: "醬包是關鍵 — 用一半" }],
        [{ en: "滷豆干 Braised dried tofu", zh: "滷豆干" }, "~600–900+mg", "bad",
          { en: "Soaks up soy-sauce sodium", zh: "吸收滷汁醬油鈉" }],
        [{ en: "百頁豆腐 Hundred-layer tofu", zh: "百頁豆腐" }, { en: "high", zh: "高" }, "bad",
          { en: "High fat + high Na — worst tofu choice", zh: "高油 + 高鈉 — 最差的豆腐選擇" }],
        [{ en: "雞蛋豆腐 Egg tofu", zh: "雞蛋豆腐" }, { en: "very high", zh: "極高" }, "bad",
          { en: "Made with salted soy — Na 150× regular tofu", zh: "含鹽醬油製成 — 鈉是一般豆腐 150 倍" }],
      ],
    },
    drinks: {
      ttl: { en: "Drink options", zh: "飲料選擇" },
      head: { en: ["Item", "kcal", "Sodium", "Protein", "Notes"],
              zh: ["品項", "熱量", "鈉", "蛋白", "備註"] },
      rows: [
        [{ en: "義美無加糖厚濃豆奶 I-Mei Unsweetened Rich", zh: "義美無加糖厚濃豆奶" }, "~228", "~30–50mg", "~21.2g",
          { en: "Highest protein", zh: "蛋白質最高" }],
        [{ en: "光泉無加糖濃豆漿 Kuang Chuan Dense", zh: "光泉無加糖濃豆漿" }, "~190", "~30–50mg", "~19.1g",
          { en: "High protein, low Na", zh: "高蛋白、低鈉" }],
        [{ en: "光泉無加糖黑豆漿 Black soy milk", zh: "光泉無加糖黑豆漿" }, "~142", "~30–50mg", "~14g",
          { en: "Low-cal; black soy may aid UA", zh: "低卡；黑豆可能助尿酸" }],
        [{ en: "健康穀物豆漿 Healthy Grain Soy Milk (400ml)", zh: "健康穀物豆漿（400ml）" }, "~140", "~100mg", "~12g",
          { en: "Health-claim certified for lipid regulation", zh: "通過健康食品認證的血脂調節" }],
        [{ en: "Unsweetened tea 無糖茶", zh: "無糖茶" }, "0", "~0mg", "0g",
          { en: "Zero burden", zh: "零負擔" }],
      ],
    },
    beverage: {
      ttl: { en: "All-day beverage strategy — every cup has a metabolic purpose", zh: "全日飲料策略 — 每杯都有代謝目的" },
      sub: { en: "Zero sugary drinks all day. Updated 2026-04-21: matcha → single lunch latte; NOW EGCG capsule discontinued; hibiscus separated from goji.",
             zh: "全天零含糖飲料。2026-04-21 更新：抹茶 → 午餐單杯拿鐵；NOW EGCG 已停用；洛神花與枸杞分開。" },
      head: { en: ["Time", "Drink", "Metabolic target"],
              zh: ["時間", "飲料", "代謝目標"] },
      rows: [
        [{ en: "Breakfast", zh: "早餐" },
          { en: "Yogurt blend (no matcha; cacao 5–10g + L-citrulline 2g)", zh: "優格飲（不放抹茶；可可 5–10g + 瓜胺酸 2g）" },
          { en: "Cocoa flavanols (BP + FMD) + NO precursor + probiotics", zh: "可可 flavanols（BP + FMD）+ NO 前體 + 益生菌" }],
        [{ en: "~9:30", zh: "~9:30" },
          { en: "Hibiscus tea cup 1 (calyx 2g / 240 mL)", zh: "洛神花茶 第 1 杯（萼 2g / 240 mL）" },
          { en: "BP −7.58 mmHg meta (Serban 2015) + LDL −12% + UA (XO inhibition)", zh: "BP −7.58 mmHg meta（Serban 2015）+ LDL −12% + 尿酸（XO 抑制）" }],
        [{ en: "Morning", zh: "上午" },
          { en: "Water 500–700 mL", zh: "白水 500–700 mL" },
          { en: "Base hydration + renal UA clearance", zh: "基礎補水 + 腎臟尿酸清除" }],
        [{ en: "11:30 (pre-lunch)", zh: "11:30（午餐前）" },
          { en: "Psyllium husk 5g + 240–350 mL water", zh: "Psyllium husk 5g + 240–350 mL 水" },
          { en: "LDL −9.69 mg/dL meta (Jovanovski 2018); bile acid binding", zh: "LDL −9.69 mg/dL meta（Jovanovski 2018）；膽汁酸結合" }],
        [{ en: "Lunch 12:00", zh: "午餐 12:00" },
          { en: "Self-made italian matcha latte 400 mL (matcha 2–3g + whole milk ~300 mL)", zh: "自泡義式抹茶拿鐵 400 mL（抹茶 2–3g + 全脂奶 300 mL）" },
          { en: "Only matcha source all day. EGCG ~48–95 mg sub-RCT dose; sugar-drink replacement", zh: "全天唯一抹茶來源。EGCG ~48–95 mg 低於 RCT 劑量；含糖飲替代" }],
        [{ en: "14:00–14:30", zh: "14:00–14:30" },
          { en: "Hibiscus tea cup 2 (2g / 240 mL)", zh: "洛神花茶 第 2 杯（2g / 240 mL）" },
          { en: "Reduce to 1 cup if home BP <110/70", zh: "家中 BP <110/70 減為 1 杯" }],
        [{ en: "15:00–16:00", zh: "15:00–16:00" },
          { en: "Pumpkin seeds 30g + water", zh: "南瓜籽 30g + 水" },
          { en: "Zn + Mg + phytosterol + tryptophan. NO 72% chocolate stacking.", zh: "鋅 + 鎂 + phytosterol + 色胺酸。72% 巧克力不堆疊。" }],
        [{ en: "16:30", zh: "16:30" },
          { en: "Psyllium husk 5g + 240–350 mL (dose 2)", zh: "Psyllium husk 5g + 240–350 mL（第 2 劑）" },
          { en: "Before 17:00 cutoff; 30-min buffer pre-dinner", zh: "17:00 截止前；晚餐前留 30 分鐘 buffer" }],
        [{ en: "17:00", zh: "17:00" },
          { en: "Tea + psyllium cutoff; plain water sips only", zh: "茶 + psyllium 截止；僅小啜白水" },
          { en: "Prevent nocturia", zh: "避免夜尿" }],
        [{ en: "18:30", zh: "18:30" },
          { en: "Dinner (UberEats, highest-fat meal)", zh: "晚餐（UberEats，最高脂餐）" },
          { en: "Fish oil ×4 only (EGCG capsule discontinued 2026-04-21)", zh: "魚油 ×4（EGCG 膠囊已於 2026-04-21 停用）" }],
        [{ en: "2 hr pre-bed", zh: "睡前 2 小時" },
          { en: "Stop liquids; sips only if thirsty", zh: "停止液體；口渴僅小啜" },
          { en: "Prevent nocturia from interrupting sleep", zh: "避免夜尿打斷睡眠" }],
      ],
      note: {
        ttl: { en: "Matcha — role downgraded to lunch latte only (2026-04-21)", zh: "抹茶 — 角色降級為午餐拿鐵（2026-04-21）" },
        body: {
          en: "Matcha EGCG 73–119 mg/cup [ConsumerLab 2018] + L-theanine. Current: 1 self-made italian matcha latte at lunch (2–3g powder + ~300 mL whole milk) — EGCG ~48–95 mg/day, further reduced 25–30% by milk casein (Egert 2013). BELOW RCT-effective 200–500 mg/day (EFSA 2018). LDL responsibility transferred to psyllium husk 10g/day (Jovanovski 2018 −9.69 mg/dL). NOW EGCG capsule discontinued after AST 27→38 + EFSA >338 mg single-dose hepatotoxicity signal. If LDL >150 at July 2026 recheck, add 1g matcha to breakfast (~70–130 mg total) before statin discussion.",
          zh: "抹茶 EGCG 73–119 mg/杯 [ConsumerLab 2018] + L-茶胺酸。現況：午餐自泡義式抹茶拿鐵 1 杯（2–3g + 全脂奶 ~300 mL）— EGCG ~48–95 mg/日，再被牛奶 casein 降 25–30%（Egert 2013）。低於 RCT 200–500 mg/日有效劑量（EFSA 2018）。LDL 責任轉至 psyllium husk 10g/日（Jovanovski 2018 −9.69 mg/dL）。NOW EGCG 已於 AST 27→38 + EFSA >338 mg 單次肝毒性訊號後停用。若 7 月複檢 LDL >150，於 statin 討論前先加早餐 1g 抹茶（合 ~70–130 mg）。",
        },
      },
    },
    dinnerBrands: {
      ttl: { en: "Dinner — healthy meal delivery (UberEats)", zh: "晚餐 — 健康餐盒外送（UberEats）" },
      familyNote: {
        en: "Family constraint: 2 adults + 2 kids share 2 boxes. Don't change structure — micro-optimize: (1) half rice to kids saves 100–140 kcal carbs; (2) grilled/braised chicken leg ~30g protein, no fried pork; (3) keep tofu/tea eggs in fridge to top up; (4) tell shop 「少鹽少醬」.",
        zh: "家庭限制：2 大 + 2 小 共用 2 盒。不改結構，微調：(1) 半飯給小孩省 100–140 kcal 碳水；(2) 烤/滷雞腿 ~30g 蛋白，不要炸排骨；(3) 冰箱備豆腐/茶葉蛋補蛋白；(4) 跟店家說「少鹽少醬」。",
      },
      head: { en: ["Brand", "Feature", "Recommended", "Price"],
              zh: ["品牌", "特色", "推薦品項", "價格"] },
      rows: [
        [{ en: "Easy Eat 健康餐盒", zh: "Easy Eat 健康餐盒" },
          { en: "4.83★, diverse proteins", zh: "4.83★，蛋白質多元" },
          { en: "Sous vide chicken 532 kcal / salt-grilled mackerel / pan-seared chicken leg", zh: "舒肥雞胸 532 kcal / 鹽烤鯖魚 / 嫩煎雞腿" },
          "NT$100–140"],
        [{ en: "Less Salt 健康餐盒", zh: "Less Salt 健康餐盒" },
          { en: "4.85★, low oil & salt", zh: "4.85★，少油少鹽" },
          { en: "Pulled chicken / seared salmon / garlic tilapia", zh: "手撕雞 / 煎鮭魚 / 蒜味鯛魚" },
          "NT$100–145"],
        [{ en: "享鮮健康餐盒 Enjoy Fresh", zh: "享鮮健康餐盒" },
          { en: "4.9★, olive-oil sous vide", zh: "4.9★，橄欖油舒肥" },
          { en: "Sous vide chicken / flat iron beef / kimchi pork; half-rice option", zh: "舒肥雞 / 板腱牛 / 泡菜豬，可選半飯" },
          "NT$90–145"],
        [{ en: "GET POWER 餐盒", zh: "GET POWER 餐盒" },
          { en: "4.9★, high protein", zh: "4.9★，高蛋白" },
          { en: "Pick chicken or fish per daily menu", zh: "依菜單選雞或魚" },
          "NT$100–130"],
        [{ en: "常常好食 (frozen)", zh: "常常好食（冷凍）" },
          { en: "Nationwide delivery, 3-min microwave", zh: "全台宅配，3 分鐘微波" },
          { en: "Calorie-control plan ~403 kcal / Na 444mg", zh: "卡路里控制餐 ~403 kcal / 鈉 444mg" },
          "NT$130–150"],
      ],
      mantra: {
        en: "Order mantra: search «healthy meal box» → pick chicken or fish → order «half rice» → avoid fried items and starchy sauces.",
        zh: "點餐口訣：搜「健康餐盒」→ 選雞或魚 → 點「半飯」→ 避開炸物和勾芡醬汁。",
      },
    },
    principles: {
      ttl: { en: "5 convenience-store shopping principles", zh: "超商採購 5 原則" },
      items: {
        en: [
          "Flip to the back and check sodium first — every package.",
          "Steamed sweet potato is your best ally — ultra-low Na, high K, high fiber.",
          "Salad dressing is a hidden sodium bomb — use half or skip.",
          "DIY individual-item assembly gives best sodium control — more flexible than pre-made boxes.",
          "Look for the Simple Fit series — 7-11's product line designed for health.",
        ],
        zh: [
          "翻背面看「鈉」 — 每一個包裝都要看。",
          "蒸地瓜是最佳夥伴 — 超低鈉、高鉀、高纖。",
          "沙拉醬是隱藏鈉彈 — 用一半或不加。",
          "DIY 單品組裝鈉控最佳 — 比現成便當有彈性。",
          "認明 Simple Fit 系列 — 7-11 專為健康設計的產品線。",
        ],
      },
    },
    fruits: {
      ttl: { en: "Fructose in fruit — how to choose", zh: "水果中的果糖 — 怎麼選" },
      sub: { en: "Whole fruit > juice (fiber intact, slow absorption). With protein and fat (yogurt blend), absorption slows further. One serving/day, after meals.",
             zh: "整顆水果優於果汁（纖維保留、吸收慢）。配蛋白與脂肪（優格飲）吸收更慢。每日一份，餐後吃。" },
      head: { en: ["Fruit (per 100g)", "Fructose", "Suitability"],
              zh: ["水果（100g）", "果糖", "適合度"] },
      rows: [
        [{ en: "Guava 芭樂", zh: "芭樂" }, "~2–3g", { en: "Excellent — lowest fructose, high vit C", zh: "極佳 — 果糖最低、高維他命 C" }, "ok"],
        [{ en: "Kiwi 奇異果", zh: "奇異果" }, "~4g", { en: "Good — sleep support + vit C", zh: "佳 — 助眠 + 維他命 C" }, "ok"],
        [{ en: "Apple 蘋果", zh: "蘋果" }, "~6g", { en: "Moderate", zh: "中等" }, "warn"],
        [{ en: "Banana 香蕉", zh: "香蕉" }, "~5–6g", { en: "Moderate — K + prebiotic, use in yogurt drink", zh: "中等 — 鉀 + 益生元，可放優格飲" }, "warn"],
        [{ en: "Avocado 酪梨 (1/4)", zh: "酪梨（1/4 顆）" }, "~0.5g", { en: "Near-zero fructose — sub for banana on high-UA days", zh: "幾乎零果糖 — 高尿酸日替代香蕉" }, "ok"],
        [{ en: "Grape 葡萄", zh: "葡萄" }, "~8g", { en: "Higher — limit", zh: "偏高 — 限量" }, "warn"],
        [{ en: "Mango 芒果", zh: "芒果" }, "~7–8g", { en: "Higher — limit", zh: "偏高 — 限量" }, "warn"],
        [{ en: "Lychee 荔枝", zh: "荔枝" }, "~8–9g", { en: "High — avoid", zh: "高 — 避免" }, "bad"],
      ],
    },
  },

  // ===== Exercise =====
  exercise: {
    why: {
      en: "Isometric exercise — wall sits — is the #1 most effective exercise for lowering BP per the 2023 BJSM meta-analysis (270 RCTs, 15,827 participants). 4 sets × 2 min, 3×/week → systolic BP −12.9 mmHg over 12 weeks. Specially effective for ISH: improves vascular endothelial function and arterial compliance.",
      zh: "等長運動 — 靠牆深蹲 — 在 2023 BJSM 統合分析（270 項 RCT、15,827 名參與者）中是最有效的降壓運動。4 組 × 2 分鐘、每週 3 次，12 週收縮壓 −12.9 mmHg。特別適合 ISH：改善血管內皮功能與動脈順應性。",
    },
    technique: {
      ttl: { en: "Six key points", zh: "六大要點" },
      rows: [
        [{ en: "Back fully against wall", zh: "背部完全貼牆" }, { en: "Head, shoulders, upper & lower back. Engage core.", zh: "頭、肩、上下背全貼牆，核心收緊。" }],
        [{ en: "Foot position", zh: "腳的位置" }, { en: "Shoulder-width, ~60 cm out from wall.", zh: "與肩同寬，離牆 ~60 cm。" }],
        [{ en: "Knees don't pass toes", zh: "膝蓋不超過腳尖" }, { en: "Shins vertical; knees above ankles.", zh: "小腿垂直，膝在踝正上。" }],
        [{ en: "Knee angle", zh: "膝蓋角度" }, { en: "Start 120° (very shallow); deepen weekly to 90°.", zh: "從 120°（非常淺）開始，逐週加深至 90°。" }],
        [{ en: "Breathing", zh: "呼吸" }, { en: "Steady nose-in / mouth-out. Never hold breath.", zh: "鼻吸口呼，絕不憋氣。" }],
        [{ en: "Center of gravity", zh: "重心" }, { en: "Weight on heels, not toes.", zh: "重心在腳跟，不是腳尖。" }],
      ],
    },
    progression: [
      // [week, angle, sec, label{en,zh}]
      [1, 120, 15,  { en: "Adaptation", zh: "適應" }],
      [2, 120, 22,  { en: "Increase duration", zh: "增加時間" }],
      [3, 105, 28,  { en: "Deepen angle", zh: "加深角度" }],
      [4, 100, 30,  { en: "Build intensity", zh: "建立強度" }],
      [5, 100, 38,  { en: "Build", zh: "進展" }],
      [6, 100, 45,  { en: "Build", zh: "進展" }],
      [7, 100, 52,  { en: "Build", zh: "進展" }],
      [8, 100, 60,  { en: "Build", zh: "進展" }],
      [9, 95, 75,   { en: "Push", zh: "推進" }],
      [10, 92, 90,  { en: "Push", zh: "推進" }],
      [11, 90, 105, { en: "Target zone", zh: "達標區" }],
      [12, 90, 120, { en: "Target — 2 min", zh: "達標 — 2 分鐘" }],
    ],
    weekplan: {
      head: { en: ["Day", "Activity", "Duration", "When"], zh: ["日", "活動", "時長", "時間"] },
      rows: [
        [{ en: "Mon", zh: "一" }, { en: "Brisk walk + wall sits", zh: "快走 + 靠牆深蹲" }, "20 + 14 min", { en: "Evening 19:00", zh: "晚間 19:00" }],
        [{ en: "Tue", zh: "二" }, { en: "Exercise snacks ×3", zh: "運動零食 ×3" }, "5 min × 3", { en: "Throughout day", zh: "分散全天" }],
        [{ en: "Wed", zh: "三" }, { en: "Brisk walk", zh: "快走" }, "20 min", { en: "Commute / evening", zh: "通勤或晚間" }],
        [{ en: "Thu", zh: "四" }, { en: "Wall sits + bodyweight", zh: "靠牆深蹲 + 徒手" }, "14 + 10 min", { en: "Evening, home", zh: "晚間在家" }],
        [{ en: "Fri", zh: "五" }, { en: "Brisk walk + snacks ×2", zh: "快走 + 零食 ×2" }, "20 + 10 min", { en: "Spread", zh: "分散" }],
        [{ en: "Sat", zh: "六" }, { en: "Family activity day", zh: "家庭活動日" }, "30 min", { en: "With family", zh: "全家一起" }],
        [{ en: "Sun", zh: "日" }, { en: "Light stretching", zh: "輕度伸展" }, "10 min", { en: "Any time", zh: "任何時間" }],
      ],
    },
    selfCheck: {
      ttl: { en: "Self-check during wall sits", zh: "靠牆深蹲自檢" },
      head: { en: ["Check", "Correct", "Warning", "Fix"],
              zh: ["檢查點", "正確", "警訊", "修正"] },
      rows: [
        [{ en: "Back", zh: "背部" }, { en: "Fully against wall", zh: "完全貼牆" },
          { en: "Lower back arches away", zh: "下背離牆" }, { en: "Slide up — shallower squat", zh: "上滑 — 蹲淺一點" }],
        [{ en: "Knees", zh: "膝蓋方向" }, { en: "Aligned with toes", zh: "對齊腳尖" },
          { en: "Collapsing inward", zh: "內夾" }, { en: "Turn toes out 10–15°", zh: "腳尖外開 10–15°" }],
        [{ en: "Knee position", zh: "膝位置" }, { en: "Above ankles", zh: "在腳踝正上方" },
          { en: "Past the toes", zh: "超過腳尖" }, { en: "Step feet forward half a step", zh: "雙腳前移半步" }],
        [{ en: "Heels", zh: "腳跟" }, { en: "Firmly planted", zh: "扎實貼地" },
          { en: "Lifting off", zh: "翹起" }, { en: "Feet too close to wall — step forward", zh: "離牆太近 — 前移" }],
        [{ en: "Breathing", zh: "呼吸" }, { en: "Steady, nose in / mouth out", zh: "穩定鼻吸口呼" },
          { en: "Holding breath / gasping", zh: "憋氣 / 喘" }, { en: "Slow pace, reduce depth", zh: "放慢節奏、減少深度" }],
        [{ en: "Body", zh: "身體" }, { en: "Upright against wall", zh: "直立貼牆" },
          { en: "Leaning forward", zh: "前傾" }, { en: "End this set", zh: "結束本組" }],
      ],
    },
    phases: {
      ttl: { en: "3-phase weekly volume", zh: "三階段每週運動量" },
      items: [
        { ph: "1", range: { en: "Months 1–2", zh: "第 1–2 月" }, vol: "120–150 min/wk",
          body: { en: "Build foundation. Brisk walks 15→20 min, 4–6k steps. Wall sits weeks 1–4. Exercise snacks (calf raises, wall push-ups). Family activity 30 min. 1 rest day.",
                  zh: "打基礎。快走 15→20 分、4–6k 步。靠牆深蹲第 1–4 週。運動零食（小腿上提、牆壁伏地挺身）。家庭活動 30 分。每週 1 休。" } },
        { ph: "2", range: { en: "Months 3–4", zh: "第 3–4 月" }, vol: "170–210 min/wk",
          body: { en: "Build intensity. Walks 30 min with intervals (3 min mod + 1 min accel — no sprints). Wall sits at target 4×2 min. Bodyweight strength: 3-round circuits (push-ups 10–12, squats 12–15, reverse lunges 8–10/side, plank 30–45s, glute bridges 10–12), 2–3×/week. 7,000–8,500 steps/day.",
                  zh: "強化強度。快走 30 分含間歇（3 分中速 + 1 分加速 — 不衝刺）。靠牆深蹲達標 4×2 分。徒手肌力 3 輪循環（伏地挺身 10–12、深蹲 12–15、反弓步 8–10/側、平板 30–45 秒、臀橋 10–12），每週 2–3 次。每日 7,000–8,500 步。" } },
        { ph: "3", range: { en: "Months 5–6", zh: "第 5–6 月" }, vol: "250–300 min/wk",
          body: { en: "Optimize. Walks 35–40 min with intervals, 8.5–10k steps. Strength 3–4 rounds advanced (Bulgarian split squats, pike push-ups, single-leg glute bridges). Wall sits 2×/week maintenance. Weekend family 45–60 min.",
                  zh: "優化。快走 35–40 分含間歇、8.5–10k 步。肌力 3–4 輪含進階動作（保加利亞分腿蹲、pike 伏地挺身、單腿臀橋）。靠牆深蹲降為 2×/週維持。週末家庭活動延長至 45–60 分。" } },
      ],
    },
  },

  // ===== Supplements =====
  supps: [
    { name: "Omega-3 Fish Oil rTG", target: { en: "TG ↓ / SBP ↓ / anti-inflammatory", zh: "三酸甘油酯 ↓ / 收縮壓 ↓ / 抗發炎" },
      dose: "4 caps · ~2g EPA+DHA", time: { en: "All 4 after dinner", zh: "晚餐後 4 顆" }, cost: "2,000–2,250", color: "var(--heart)" },
    { name: "Psyllium Husk", target: { en: "LDL −9.69 mg/dL · bile acid binding", zh: "LDL −9.69 mg/dL · 膽汁酸結合" },
      dose: "5g × 2 (10g)", time: { en: "11:30 + 16:30", zh: "11:30 + 16:30" }, cost: "150–300", color: "var(--metabolic)" },
    { name: "D3 + K2", target: { en: "Vit D / hsCRP / BP / Ca-routing", zh: "維他命 D / hsCRP / 血壓 / 鈣質導向" },
      dose: "D3 2000 IU + K2 100 mcg", time: { en: "Breakfast blend", zh: "早餐果昔" }, cost: "200–400", color: "var(--weight)" },
    { name: "Hibiscus Calyces", target: { en: "SBP −7.58 / DBP −3.53 · LDL −12% · UA (XO)", zh: "SBP −7.58 / DBP −3.53 · LDL −12% · 尿酸 (XO)" },
      dose: "2g × 2 cups", time: { en: "9:30 + 14:00", zh: "9:30 + 14:00" }, cost: "100–200", color: "var(--heart)" },
    { name: "L-Citrulline", target: { en: "NO precursor · vasodilation · renal perfusion", zh: "一氧化氮前體 · 血管舒張 · 腎臟灌流" },
      dose: "2 g", time: { en: "Breakfast blend", zh: "早餐果昔" }, cost: "200–350", color: "var(--sleep)" },
    { name: "Mg Glycinate", target: { en: "Sleep · BP · HbA1c adjunct", zh: "睡眠 · 血壓 · HbA1c 輔助" },
      dose: "200–400 mg", time: { en: "Bedtime", zh: "睡前" }, cost: "300–500", color: "var(--uric)" },
    { name: "Tart Cherry (CherryPURE)", target: { en: "UA −37% (4-week RCT) · CRP ↓ · sleep", zh: "尿酸 −37%（4 週 RCT）· CRP ↓ · 助眠" },
      dose: "1000–2000 mg", time: { en: "Bedtime", zh: "睡前" }, cost: "370–740", color: "var(--uric)" },
    { name: "Whey Protein", target: { en: "MPS · satiety · lean mass on cut", zh: "肌肉合成 · 飽足感 · 減重保肌" },
      dose: "30 g (25–30 g protein)", time: { en: "Breakfast blend", zh: "早餐果昔" }, cost: "800–1,200", color: "var(--metabolic)" },
    { name: "Pumpkin Seeds (food)", target: { en: "Zn + Mg + phytosterol + tryptophan", zh: "鋅 + 鎂 + 植物固醇 + 色胺酸" },
      dose: "30 g", time: { en: "Afternoon 15:00", zh: "下午 15:00" }, cost: "300–500", color: "var(--weight)" },
  ],

  // ===== Daily Routine — 24h timeline events =====
  routine: [
    // hour, label{en,zh}, cat
    [5.5,  { en: "Wake", zh: "起床" }, "sleep"],
    [7,    { en: "Breakfast blend", zh: "早餐果昔" }, "meal"],
    [9.5,  { en: "Hibiscus #1", zh: "洛神花 ①" }, "supp"],
    [11.5, { en: "Psyllium #1", zh: "洋車前子 ①" }, "supp"],
    [12,   { en: "Lunch", zh: "午餐" }, "meal"],
    [12.7, { en: "Post-lunch walk", zh: "餐後快走" }, "exer"],
    [14,   { en: "Hibiscus #2", zh: "洛神花 ②" }, "supp"],
    [15.5, { en: "Pumpkin seeds", zh: "南瓜籽" }, "supp"],
    [16.5, { en: "Psyllium #2", zh: "洋車前子 ②" }, "supp"],
    [17,   { en: "Fluid cutoff", zh: "停止補水" }, "cutoff"],
    [18.5, { en: "Dinner + Omega-3", zh: "晚餐 + 魚油" }, "meal"],
    [19,   { en: "Wall sits", zh: "靠牆深蹲" }, "exer"],
    [20,   { en: "Leg elevation", zh: "抬腿" }, "exer"],
    [20.5, { en: "Bed · Mg + Cherry", zh: "就寢 · 鎂 + 酸櫻桃" }, "sleep"],
  ],

  // ===== Daily checklist =====
  checklist: {
    en: [
      ["water_pre17", "Hydration completed before 17:00 (2.5–3.0 L)"],
      ["sodium",      "Stayed under 1,500 mg sodium today"],
      ["walk",        "30-min post-lunch walk"],
      ["wallsit",     "Wall sits — 4 sets × current target"],
      ["psyllium",    "Psyllium husk × 2 (11:30 & 16:30)"],
      ["hibiscus",    "Hibiscus × 2 cups (9:30 & 14:00)"],
      ["omega",       "Omega-3 × 4 capsules with dinner"],
      ["mg_cherry",   "Magnesium + tart cherry at bedtime"],
      ["leg_elev",    "Leg elevation 15 min before bed"],
      ["bed_530",     "Did not leave bed before 5:30"],
      ["bp_log",      "BP measured & logged"],
      ["weight_log",  "Weight measured & logged"],
    ],
    zh: [
      ["water_pre17", "17:00 前完成補水（2.5–3.0 L）"],
      ["sodium",      "今日鈉攝取 < 1,500 mg"],
      ["walk",        "午餐後快走 30 分鐘"],
      ["wallsit",     "靠牆深蹲 — 4 組 × 當週目標"],
      ["psyllium",    "洋車前子 × 2（11:30 & 16:30）"],
      ["hibiscus",    "洛神花 × 2 杯（9:30 & 14:00）"],
      ["omega",       "晚餐 Omega-3 × 4 顆"],
      ["mg_cherry",   "睡前鎂 + 酸櫻桃"],
      ["leg_elev",    "睡前抬腿 15 分鐘"],
      ["bed_530",     "5:30 前未離床"],
      ["bp_log",      "已量測並記錄血壓"],
      ["weight_log",  "已量測並記錄體重"],
    ],
  },

  // ===== Timeline / months =====
  months: [
    { num: 1, ttl: { en: "Sleep first", zh: "先修睡眠" },
              body: { en: "OSA screen, fluid timing, leg elevation, 5:30 rule.", zh: "OSA 篩檢、補水時機、抬腿、5:30 規則。" } },
    { num: 2, ttl: { en: "Foundation", zh: "打基礎" },
              body: { en: "Brisk walk routine, sodium audit, supplement stack settled.", zh: "快走、鈉審視、保健品穩定。" } },
    { num: 3, ttl: { en: "Wall sit ramp", zh: "靠牆深蹲進展" },
              body: { en: "Hold time 60 s, sodium < 1,500 mg, Body Battery ≥ 65.", zh: "撐 60 秒、鈉 < 1,500 mg、身體電量 ≥ 65。" } },
    { num: 4, ttl: { en: "First labs", zh: "首次回診" },
              body: { en: "BP, lipids, UA recheck. Adjust fish oil if LDL ↑.", zh: "血壓、血脂、尿酸複檢。LDL 上升則調魚油。" } },
    { num: 5, ttl: { en: "Optimize", zh: "優化" },
              body: { en: "Hold 90–120 s, intervals in walks, weight ~66 kg.", zh: "撐 90–120 秒、走路間歇、體重 ~66 kg。" } },
    { num: 6, ttl: { en: "Goal check", zh: "目標檢視" },
              body: { en: "65 kg target, BP 120/75, all four markers in range.", zh: "65 kg、血壓 120/75、四項指標達標。" } },
  ],

  // ===== Safety =====
  safety: [
    { ttl: { en: "Diastolic floor", zh: "舒張壓下限" },
      cls: "warn",
      body: { en: "Diastolic already 75. Some BP drugs lower both systolic and diastolic, risking diastolic < 60. Lifestyle interventions first.",
              zh: "舒張壓已 75。部分降壓藥同時降收縮與舒張壓，可能使舒張壓 < 60。生活方式介入優先。" } },
    { ttl: { en: "Uric acid 8.9 — referral pending", zh: "尿酸 8.9 — 轉診中" },
      cls: "bad",
      body: { en: "Constitutional. Avoid high-intensity exercise (lactic acid blocks UA excretion). Hydrate 500 mL pre-exercise + 200 mL/15 min during.",
              zh: "體質性。避免高強度運動（乳酸抑制尿酸排泄）。運動前 500 mL，運動中每 15 分 200 mL。" } },
    { ttl: { en: "Iron + polyphenol spacing", zh: "鐵與多酚間隔" },
      cls: "info",
      body: { en: "Hibiscus / tea polyphenols inhibit non-heme iron. Space ≥ 1 hr from red meat / iron supplements.",
              zh: "洛神花／茶的多酚抑制非血基質鐵吸收。與紅肉／鐵劑間隔 ≥ 1 小時。" } },
    { ttl: { en: "Drug interactions", zh: "藥物交互作用" },
      cls: "info",
      body: { en: "Hibiscus accelerates acetaminophen elimination; PK interactions with HCTZ, chloroquine, diclofenac.",
              zh: "洛神花加速 acetaminophen 代謝；與 HCTZ、chloroquine、diclofenac 有藥動學交互。" } },
    { ttl: { en: "Hypotension watch", zh: "低血壓警戒" },
      cls: "warn",
      body: { en: "If home BP < 110/70, drop to 1 cup hibiscus and pause citrulline.",
              zh: "若家中血壓 < 110/70，洛神花減為 1 杯，瓜胺酸暫停。" } },
    { ttl: { en: "EGCG / liver", zh: "EGCG / 肝臟" },
      cls: "bad",
      body: { en: "NOW EGCG capsule discontinued 2026-04-21 after AST 27→38; EFSA flags hepatotoxicity > 338 mg single dose.",
              zh: "2026-04-21 停用 NOW EGCG（AST 27→38）；EFSA 警示單次劑量 > 338 mg 肝毒性風險。" } },
  ],

  // ===== Tracker — last 14 days (4/21–5/4, real Garmin / cuff data) =====
  tracker: {
    // [SBP, DBP] — gaps filled with prior reading
    bp: [
      [121,75], [125,71], [126,68], [121,72], [128,74], [122,70], [129,75], [127,75], [127,72], [127,72], [127,72], [127,72], [113,68], [113,68],
    ],
    // 4/21–5/4 daily weight (kg)
    weight: [68.6, 68.5, 68, 67.9, 68.4, 68.6, 68.9, 68.4, 68.2, 67.8, 67.9, 67.8, 68.7, 69.1],
    // Garmin Sleep Score
    sleep:  [74, 69, 73, 71, 75, 64, 64, 69, 64, 71, 52, 69, 77, 77],
    // Body Battery waking
    bb:     [56, 60, 59, 34, 66, 60, 57, 57, 58, 51, 47, 41, 54, 49],
  },

  // ===== Running — started 2026-04-26 =====
  running: {
    intro: {
      en: "First run logged 2026-04-26 (DOMS appeared 4/27 at intensity 3/10). Running adds aerobic stress on top of wall sits and walks — but with UA 8.9 it must be paced carefully: lactic acid blocks uric-acid excretion, so high-intensity efforts are off the table for now.",
      zh: "首次跑步紀錄為 4/26（4/27 出現大腿 DOMS 強度 3/10）。跑步在靠牆深蹲與快走之上加入有氧負荷——但尿酸 8.9 必須謹慎控速：乳酸會抑制尿酸排泄，目前不做高強度。",
    },
    rules: {
      ttl: { en: "Three hard rules (UA 8.9 + ISH context)", zh: "三條硬規則（尿酸 8.9 + 單純收縮期高血壓背景）" },
      items: {
        en: [
          "Hydrate: 500 mL 30 min pre-run · 200 mL every 15 min during · 500 mL post — UA excretion priority.",
          "Heart-rate ceiling: Zone 2 only — talk-test pace, ≤ 70% HRmax (~135 bpm). Above this lactic acid spikes UA.",
          "DOMS rule: if soreness ≥ 4/10, switch to walk + stretch. No back-to-back run days for first 4 weeks.",
        ],
        zh: [
          "補水：跑前 30 分 500 mL · 跑中每 15 分 200 mL · 跑後 500 mL — 尿酸排泄優先。",
          "心率上限：僅 Zone 2 — 可對話配速、≤ 70% HRmax（~135 bpm）。超過則乳酸飆升、尿酸難排。",
          "DOMS 規則：肌肉痠 ≥ 4/10 改為走路 + 伸展。前 4 週不做連續兩天跑步。",
        ],
      },
    },
    // 8-week run-walk progression (Couch-to-5K adapted, Z2-capped)
    progression: [
      // [week, label{en,zh}, format{en,zh}, totalMin, runFrac]
      [1, { en: "Foundation", zh: "打底" },
          { en: "Run 1' / Walk 2' × 8", zh: "跑 1 分 / 走 2 分 × 8" }, 24, 0.33],
      [2, { en: "Foundation", zh: "打底" },
          { en: "Run 1.5' / Walk 2' × 8", zh: "跑 1.5 分 / 走 2 分 × 8" }, 28, 0.43],
      [3, { en: "Build", zh: "進展" },
          { en: "Run 2' / Walk 2' × 7", zh: "跑 2 分 / 走 2 分 × 7" }, 28, 0.50],
      [4, { en: "Deload", zh: "減量" },
          { en: "Run 2' / Walk 1.5' × 7", zh: "跑 2 分 / 走 1.5 分 × 7" }, 24.5, 0.57],
      [5, { en: "Build", zh: "進展" },
          { en: "Run 3' / Walk 2' × 6", zh: "跑 3 分 / 走 2 分 × 6" }, 30, 0.60],
      [6, { en: "Build", zh: "進展" },
          { en: "Run 5' / Walk 2' × 4", zh: "跑 5 分 / 走 2 分 × 4" }, 28, 0.71],
      [7, { en: "Push", zh: "推進" },
          { en: "Run 8' / Walk 2' × 3", zh: "跑 8 分 / 走 2 分 × 3" }, 30, 0.80],
      [8, { en: "Continuous", zh: "連續" },
          { en: "Run 20' continuous", zh: "連續跑 20 分" }, 25, 1.00],
    ],
    schedule: {
      ttl: { en: "Weekly placement — running fits between wall sits, doesn't replace them", zh: "每週安排 — 跑步插在靠牆深蹲之間，不取代深蹲" },
      head: { en: ["Day", "Primary", "Why"], zh: ["日", "主項", "原因"] },
      rows: [
        [{ en: "Mon", zh: "一" }, { en: "Run-walk Z2", zh: "跑走 Z2" },
          { en: "Fresh legs from weekend", zh: "週末恢復後雙腿狀態好" }],
        [{ en: "Tue", zh: "二" }, { en: "Wall sits + stretch", zh: "靠牆深蹲 + 伸展" },
          { en: "BP-lowering isometric — different stimulus", zh: "等長運動降壓，不同刺激" }],
        [{ en: "Wed", zh: "三" }, { en: "Brisk walk 25 min", zh: "快走 25 分" },
          { en: "Active recovery, NEAT", zh: "主動恢復、提升非運動消耗" }],
        [{ en: "Thu", zh: "四" }, { en: "Run-walk Z2", zh: "跑走 Z2" },
          { en: "≥48 h since Mon run", zh: "距週一跑步 ≥48 小時" }],
        [{ en: "Fri", zh: "五" }, { en: "Wall sits", zh: "靠牆深蹲" },
          { en: "Maintain BP protocol", zh: "維持降壓主軸" }],
        [{ en: "Sat", zh: "六" }, { en: "Long walk / family", zh: "長距離走路 / 家庭日" },
          { en: "Volume without joint stress", zh: "累積量但不傷關節" }],
        [{ en: "Sun", zh: "日" }, { en: "Stretch + leg elevation", zh: "伸展 + 抬腿" },
          { en: "Recovery for the week", zh: "全週恢復" }],
      ],
    },
    metrics: {
      ttl: { en: "Watch these on your runs", zh: "跑步時觀察這些" },
      items: [
        ["HR avg", "≤ 135 bpm (Z2)", "var(--heart)"],
        ["Cadence", "170–180 spm", "var(--metabolic)"],
        ["Pace", { en: "comfortable, can talk", zh: "舒服、能說話" }, "var(--sleep)"],
        ["Post-run UA signs", { en: "no toe pain at 24-48 h", zh: "24-48h 無拇趾痛" }, "var(--uric)"],
      ],
    },
  },

  // ===== Supplements detail (extended) =====
  suppsDetail: {
    fullStack: {
      ttl: { en: "Complete supplement priority & monthly cost (2026-04-21)", zh: "保健品優先序與月成本（2026-04-21）" },
      head: { en: ["Priority", "Item", "Daily dose", "Timing", "Monthly NTD"],
              zh: ["優先", "品項", "每日劑量", "時機", "月費 NTD"] },
      rows: [
        ["1", "Fish oil 80% EPA+DHA (Da Yan)", "4 caps (~2g EPA+DHA)",
          { en: "All 4 after dinner", zh: "晚餐後 4 顆" }, "2,000–2,250"],
        ["2", "Psyllium husk 🆕", "5g × 2 (10g)",
          { en: "11:30 + 16:30", zh: "11:30 + 16:30" }, "150–300"],
        ["3", "D3K2", "D3 2000 IU + K2 100 mcg",
          { en: "Breakfast yogurt blend", zh: "早餐優格飲" }, "200–400"],
        ["4", "Hibiscus calyces 🆕", "2g × 2 cups",
          { en: "9:30 + 14:00", zh: "9:30 + 14:00" }, "100–200"],
        ["5", "L-Citrulline", "2g (breakfast only)",
          { en: "Breakfast yogurt blend", zh: "早餐優格飲" }, "200–350"],
        ["6", "Mg glycinate", "200–400 mg",
          { en: "Bedtime", zh: "睡前" }, "300–500"],
        ["7", "Tart Cherry (NOW Foods)", "1000–2000 mg",
          { en: "Bedtime", zh: "睡前" }, "370–740"],
        ["—", "Whey Protein", "30g",
          { en: "Breakfast yogurt blend (training day +20–30g post-workout)", zh: "早餐優格飲（訓練日訓後再 +20–30g）" }, "800–1,200"],
        ["—", "Pumpkin seeds (food)", "30g",
          { en: "Afternoon 15:00–16:00", zh: "下午 15:00–16:00" }, "300–500"],
        ["—", "Matcha powder (lunch latte)", "2–3g",
          { en: "Lunch 12:00", zh: "午餐 12:00" }, "100–150"],
      ],
      total: { en: "Active stack monthly: NT$ 4,520–6,590",
               zh: "現用組合月費：NT$ 4,520–6,590" },
      pending: [
        { item: "Creatine monohydrate (pending RT resumption)",
          dose: "3–5g", reason: { en: "Adds when RT ≥2×/week resumes", zh: "重訓 ≥2×/週後加入" }, cost: "~200" },
        { item: "NOW EGCG (discontinued 2026-04-21)",
          dose: "—", reason: { en: "AST 27→38 + EFSA hepatotoxicity signal", zh: "AST 27→38 + EFSA 肝毒性訊號" }, cost: "0" },
        { item: "NAC (not active)",
          dose: "—", reason: { en: "Removed from current stack", zh: "已從現用組合移除" }, cost: "0" },
      ],
      foodForm: {
        ttl: { en: "Food-form nutrition (already in daily meals)", zh: "食物形態營養（已在每日餐食中）" },
        body: { en: "Raw cacao 5–10g (breakfast blend, flavanols), goji 15–20g (breakfast blend, not tea), blueberries 80–100g (breakfast blend, anthocyanins), pumpkin seeds 30g (afternoon snack), mixed nuts ~30g (breakfast blend, MUFA carrier for D3K2). Food provides matrix effects supplements can't replicate.",
                zh: "生可可粉 5–10g（早餐果昔，flavanols）、枸杞 15–20g（早餐果昔，不沖泡）、藍莓 80–100g（早餐果昔，花青素）、南瓜籽 30g（下午點心）、綜合堅果 ~30g（早餐果昔，MUFA 載體助 D3K2 吸收）。食物的 matrix 效應補充劑無法取代。" },
      },
    },
    rtg: {
      ttl: { en: "Why rTG form matters (Omega-3)", zh: "為什麼 rTG 型很重要（Omega-3）" },
      head: { en: ["Form", "Full name", "Concentration", "Absorption", "Notes"],
              zh: ["型態", "全名", "濃度", "吸收率", "備註"] },
      rows: [
        ["TG", { en: "Natural triglyceride", zh: "天然三酸甘油酯型" }, "20–30%", "100% (baseline)",
          { en: "Original form, low concentration", zh: "原始型態，濃度低" }],
        ["EE", { en: "Ethyl ester", zh: "乙酯型" }, "50–90%", "~73%",
          { en: "Pancreatic enzymes break it 10–50× slower", zh: "胰酶分解慢 10–50 倍" }],
        ["rTG", { en: "Re-esterified TG", zh: "再酯化三酸甘油酯型" }, "80–95%", "~124%",
          { en: "High concentration + high absorption", zh: "高濃度 + 高吸收率" }],
      ],
      note: { en: "72-person RCT: rTG +24% over natural TG and ~1.5–1.7× more bioavailable than EE. Always take with a fat-containing meal.",
              zh: "72 人 RCT：rTG 比天然 TG +24%，比 EE 高約 1.5–1.7 倍。一定隨含脂肪餐食服用。" },
      taiwan: { en: "Taiwan MOHW caps daily EPA+DHA at 2g. 4 capsules = 1,920 mg, just under the limit.",
                zh: "衛福部每日 EPA+DHA 上限 2 公克。4 顆 = 1,920 mg，剛在上限內。" },
    },
    citrulline: {
      ttl: { en: "L-Citrulline → NO pathway → LVH adjunct (existing 11-yr LVH)", zh: "L-瓜胺酸 → NO 路徑 → LVH 輔助（已有 11 年慢性 LVH）" },
      intro: { en: "Context: ECG-confirmed LVH since 2015 (age 26), with biatrial enlargement + anterior ST elevation newly added 2026-03-25. Citrulline is NOT the primary tool — RAAS blockade (ARB / ACEi) is first-line for LVH regression (LIFE trial: losartan reduced LV mass index −25 g/m² over 4.8 yr). Citrulline's role is adjunctive: protect the NO pool that UA 8.9 is depleting via peroxynitrite, while ARB / ACEi (or other clinical decisions) catch up. NO has 5 mechanistic links to LVH:",
               zh: "背景：2015（age 26）起 ECG 確認 LVH，2026-03-25 新增雙心房擴大 + 前壁 ST 抬升。瓜胺酸**不是主力**—RAAS 阻斷（ARB / ACEi）才是 LVH regression 一線（LIFE 試驗：losartan 4.8 年降 LV mass index −25 g/m²）。瓜胺酸是輔助：在 ARB / ACEi 等臨床決策跟上前，先把尿酸 8.9 透過 peroxynitrite 耗損的 NO 池子撐住。NO 對 LVH 有 5 個機制連結：" },
      points: {
        en: [
          "Directly opposes LVH progression. NO is anti-hypertrophic via BP reduction + RAAS/SNS modulation [Ahmad 2018, PMC6164974]. In SHR/LVH rat models, eNOS dropped ~35%; L-arginine 5 weeks → eNOS +27%, heart index −53% [Ahmad et al. 2016, J Physiol Pharmacol, PMID: 27010893].",
          "Improves cardiac diastolic function. NO hastens myocardial relaxation and increases distensibility [Paulus, Heart Fail Rev 2000, PMID: 11498647]; this NO-mediated regulation is impaired in LVH.",
          "Mechanistically NO donors reduce arterial stiffness independent of BP, but whether L-citrulline itself moves stiffness markers (PWV / AIx) is not yet proven by RCTs — Hillsley 2024 trial-design review explicitly notes the current RCT base is insufficient [PMC11053694].",
          "Renal protection. NO regulates renal hemodynamics — at UA 8.9 the kidneys are stressed; NO-mediated vasodilation helps maintain GFR.",
          "UA destroys NO itself. UA → NADPH oxidase → superoxide → peroxynitrite → NO consumption + eNOS uncoupling → less NO → vicious cycle. Citrulline is the only intervention directly supplying NO substrate.",
        ],
        zh: [
          "直接對抗 LVH 進展。NO 透過降 BP + RAAS/SNS 調節抗肥厚 [Ahmad 2018, PMC6164974]。SHR/LVH 大鼠模型 eNOS 下降約 35%；L-精胺酸 5 週 → eNOS +27%、heart index −53% [Ahmad et al. 2016, J Physiol Pharmacol, PMID: 27010893]。",
          "改善心臟舒張功能。NO 加速心肌放鬆並提高心室順應性 [Paulus, Heart Fail Rev 2000, PMID: 11498647]；此 NO 介導之調節在 LVH 中受損。",
          "機制上 NO donor 可降動脈僵硬獨立於 BP，但 L-瓜胺酸本身是否能移動 PWV / AIx 標記，目前 RCT 證據不足 — Hillsley 2024 試驗設計回顧明確指出此資料缺口 [PMC11053694]。",
          "腎臟保護。NO 調節腎血流 — 尿酸 8.9 時腎臟有壓力；NO 介導之血管舒張助維持 GFR。",
          "尿酸自身會破壞 NO。UA → NADPH oxidase → 超氧化物 → peroxynitrite → 消耗 NO + eNOS 解偶聯 → NO 更少 → 惡性循環。瓜胺酸是唯一直接補 NO 合成基質的介入。",
        ],
      },
      bp: { en: "Luo 2025 meta (15 RCTs, 415 participants, l-citrulline OR watermelon): SBP −4.02 mmHg [95% CI −6.54 to −1.50], DBP −2.54 mmHg [95% CI −4.27 to −0.81] in middle-aged/older adults. Citrulline + L-arginine combination: SBP −10.44 mmHg [95% CI −13.57 to −7.31] [PMID: 40789388]. Earlier meta (Barkhidarian 2019, 8 RCTs): significant DBP reduction only in ≥6g/day studies [PMID: 30788274].",
            zh: "Luo 2025 meta（15 項 RCT、415 人，含 L-瓜胺酸或西瓜介入）：中老年 SBP −4.02 mmHg [95% CI −6.54 至 −1.50]、DBP −2.54 mmHg [95% CI −4.27 至 −0.81]。瓜胺酸 + 精胺酸組合：SBP −10.44 mmHg [95% CI −13.57 至 −7.31] [PMID: 40789388]。較早的 meta（Barkhidarian 2019，8 項 RCT）：DBP 顯著降低僅 ≥6g/日 [PMID: 30788274]。" },
      dose: { en: "Current: 2g/day at breakfast only. Below RCT 3–6g/day for BP. At 2g contributes ~1–2 mmHg in NO stack. If LDL+HDL+BP stall, escalate to breakfast 3g (single dose above threshold) before splitting. Avoid with PDE5i; pause if home BP <110/70.",
              zh: "現況：早餐 2g（不分次）。低於 RCT 3–6g/日。2g 在 NO 組合中貢獻 ~1–2 mmHg。LDL+HDL+BP 卡關時先升早餐 3g（單次過門檻），不分次。與 PDE5i（威而鋼）併用要小心；家中 BP <110/70 暫停。" },
      regression: {
        ttl: { en: "LVH regression — what's actually achievable", zh: "LVH 逆轉 — 實際可達成的範圍" },
        body: {
          en: "Yes, LVH can regress (cardiomyocytes shrink via autophagy + ubiquitin-proteasome; some interstitial fibrosis is reversible if not yet calcified). Realistic timeline with this protocol: (a) 6 months — halt progression of biatrial enlargement + prevent further wall thickening (minimum bar); (b) 1–2 yr with ARB / ACEi + sustained BP <125/75 + OSA fixed — echo LV mass starts dropping; (c) 3–5 yr — significant regression possible if fibrosis hasn't calcified. Drug class matters: ARB ~−13% LV mass, ACEi ~−10%, CCB ~−11%, β-blocker ~−6% (Klingbeil 2003 meta). Lifestyle / supplements alone cannot regress established 11-yr LVH — RAAS blockade discussion at next clinic visit is the highest-leverage step.",
          zh: "LVH 確實可逆轉（心肌細胞透過 autophagy + ubiquitin-proteasome 路徑縮回；間質纖維化若尚未鈣化部分可逆）。本計畫實際時程：(a) 6 個月 — 阻止雙心房擴大進展 + 不再增厚（最低門檻）；(b) 1–2 年配合 ARB / ACEi + BP <125/75 + OSA 修好 — echo LV mass 開始下降；(c) 3–5 年 — 若纖維化未鈣化，可顯著回縮。藥物類別差很多：ARB 約 LV mass −13%、ACEi −10%、CCB −11%、β-blocker −6%（Klingbeil 2003 meta）。**單靠生活方式 / 補品無法逆轉已存在 11 年的 LVH**—下次回診主動討論 ARB / ACEi 是槓桿最大的一步。",
        },
      },
    },
    hibiscus: {
      ttl: { en: "Hibiscus tea — strongest herbal BP evidence", zh: "洛神花茶 — 最強草本降壓證據" },
      points: {
        en: [
          "Serban C 2015 J Hypertens — meta of 5 RCTs (n=390): SBP −7.58 mmHg (95% CI −9.69 to −5.47), DBP −3.53 mmHg (−5.16 to −1.90) [PMID: 25915121].",
          "McKay DL 2010 J Nutr — RCT n=65 prehypertensive/mild HT, 3 cups/day × 6 weeks → SBP −7.2 vs placebo −1.3 mmHg (p=0.030) [PMID: 19923585].",
          "Mozaffari-Khosravi 2009 J Hum Hypertens — T2DM+HT n=60, 2 cups/day × 1 month → SBP −22 mmHg (black-tea control SBP ↑) [PMID: 18685605].",
          "Lipids — Mozaffari-Khosravi 2009: TC −8%, LDL −12%, HDL +16.7%, TG −14%.",
          "UA — Kuo CY 2012: serum UA ↓ (small pilot). Mechanism: anthocyanins + protocatechuic acid inhibit XO.",
          "Recipe: dried calyces 2g / 240 mL hot water, steep 5–10 min, optional 1 re-brew. Drink with straw (pH ~2.8 protects enamel). No sugar.",
        ],
        zh: [
          "Serban C 2015 J Hypertens — 5 項 RCT meta（n=390）：SBP −7.58 mmHg（95% CI −9.69 至 −5.47）、DBP −3.53 mmHg（−5.16 至 −1.90）[PMID: 25915121]。",
          "McKay DL 2010 J Nutr — RCT n=65 高血壓前期/輕度，3 杯/日 × 6 週 → SBP −7.2 vs 安慰劑 −1.3 mmHg（p=0.030）[PMID: 19923585]。",
          "Mozaffari-Khosravi 2009 J Hum Hypertens — T2DM+HT n=60，2 杯/日 × 1 月 → SBP −22 mmHg（紅茶對照組 SBP ↑）[PMID: 18685605]。",
          "血脂 — Mozaffari-Khosravi 2009：TC −8%、LDL −12%、HDL +16.7%、TG −14%。",
          "尿酸 — Kuo CY 2012：血清尿酸 ↓（小型試驗）。機轉：花青素 + 原兒茶酸抑制 XO。",
          "配方：乾燥花萼 2g / 240 mL 熱水沖 5–10 分鐘，可再泡 1 次。用吸管喝（pH ~2.8 護琺瑯質）。不加糖。",
        ],
      },
      safety: {
        ttl: { en: "Safety & interactions — read before starting", zh: "安全與交互作用 — 啟動前必讀" },
        items: {
          en: [
            "Iron absorption: polyphenols inhibit non-heme iron — space ≥1 hr from red meat / dark greens / iron supplements.",
            "Drug interactions: accelerates acetaminophen elimination — avoid co-dosing. PK interactions with HCTZ, chloroquine, diclofenac.",
            "Hypotension: home BP <110/70 → reduce to 1 cup/day or stop.",
            "Pregnancy: contraindicated (uterine contraction).",
            "Stacking with BP meds: on ACEi/ARB monitor for over-dipping. Training days: skip 2nd cup to avoid post-exercise vasodilation overshoot.",
          ],
          zh: [
            "鐵吸收：多酚抑制非血基質鐵 — 距紅肉/深色蔬菜/鐵劑 ≥1 小時。",
            "藥物交互：加速 acetaminophen（普拿疼）代謝 — 避免併服。與 HCTZ、chloroquine、diclofenac 有 PK 交互。",
            "低血壓：家中 BP <110/70 → 減為 1 杯/日 或停。",
            "懷孕：禁忌（子宮收縮）。",
            "與降壓藥併用：ACEi/ARB 注意過度下降。訓練日跳過第 2 杯，避免運動後血管舒張疊加。",
          ],
        },
      },
    },
    creatine: {
      ttl: { en: "Creatine monohydrate — considered, not active", zh: "肌酸 — 評估中，目前未用" },
      benefits: { en: "Grade A non-athletic benefits: bone density (Candow 2023, with RT); MPS during caloric restriction (key for 68.6→65 kg cut); cognitive function (5g/day improved memory + reaction time in older adults); insulin sensitivity via GLUT4 (Gualano 2011) — adjunct for HbA1c 5.9%.",
                  zh: "非運動員 Grade A 證據：骨密度（Candow 2023，需 RT 配合）；熱量限制下肌肉合成（68.6→65 kg 減重保肌關鍵）；認知功能（5g/日改善老年記憶+反應）；GLUT4 介導胰島素敏感度（Gualano 2011） — HbA1c 5.9% 的輔助。" },
      caveats: {
        en: [
          "Scale weight +1–2 kg water retention in first 1–2 weeks — contaminates trend toward 65 kg. Log start date, reset baseline after week 2.",
          "Serum creatinine rises ~0.1–0.3 mg/dL → CKD-EPI/MDRD eGFR shows 'worse' kidney function (NOT injury, just creatine metabolism). Critical with UA 8.9 + pending nephrology — tell nephrologist before labs, or request cystatin C-based eGFR.",
        ],
        zh: [
          "前 1–2 週體重 +1–2 kg 水分滯留 — 污染體重趨勢。需明確記錄起始日，第 2 週後重設 baseline。",
          "血清肌酸酐 +0.1–0.3 mg/dL → CKD-EPI/MDRD eGFR 公式顯示「惡化」（非傷害，是肌酸代謝）。尿酸 8.9 + 待轉診腎臟科時關鍵 — 抽血前告知腎科，或要求 cystatin C 公式 eGFR。",
        ],
      },
      trigger: { en: "Add 3–5 g/day Creapure when RT resumes ≥2×/week. Without RT, most benefits don't materialize.",
                 zh: "重訓 ≥2×/週恢復後加 3–5 g/日 Creapure。沒 RT 大部分效益不會發生。" },
    },
    plans: {
      ttl: { en: "Monthly cost — Plan A vs Plan B", zh: "月費用 — 方案 A vs 方案 B" },
      planA: {
        ttl: { en: "Plan A: Da Yan (recommended)", zh: "方案 A：大研（推薦）" },
        rows: [
          [{ en: "Da Yan German Premium Fish Oil", zh: "大研德國頂級魚油" }, "60 caps/btl",
            { en: "4/day = 2 btls", zh: "4 顆/日 = 2 瓶" }, "NT$2,000–2,250"],
          [{ en: "NOW Foods Tart Cherry", zh: "NOW Foods 酸櫻桃" }, "90 caps/btl",
            { en: "1/day = 0.33 btl", zh: "1 顆/日 = 0.33 瓶" }, "~NT$185"],
          [{ en: "Goji berries (dried)", zh: "枸杞（乾燥）" }, { en: "Bulk", zh: "散裝" }, "~600g", "~NT$200–350"],
        ],
        total: "NT$2,385–2,785",
      },
      planB: {
        ttl: { en: "Plan B: All from iHerb (budget)", zh: "方案 B：全部 iHerb（省錢）" },
        rows: [
          [{ en: "Sports Research Omega-3", zh: "Sports Research Omega-3" }, "120 caps/btl",
            { en: "2–3/day", zh: "2–3 顆/日" }, "NT$390–585"],
          [{ en: "NOW Foods Tart Cherry", zh: "NOW Foods 酸櫻桃" }, "90 caps/btl",
            { en: "1/day", zh: "1 顆/日" }, "~NT$185"],
          [{ en: "Goji berries (dried)", zh: "枸杞（乾燥）" }, { en: "Bulk", zh: "散裝" }, "~600g", "~NT$200–350"],
        ],
        total: "NT$775–1,120",
      },
      savings: { en: "Plan B saves NT$1,400–1,600/month, nearly NT$18,000/year — covers a home BP monitor, sleep clinic copays, or a year of healthy meal upgrades.",
                 zh: "方案 B 每月省 NT$1,400–1,600，一年近 NT$18,000 — 足夠買家用血壓計、睡眠門診掛號費，或一年的健康餐升級。" },
      bottom: { en: "Da Yan and Sports Research are both rTG with equivalent absorption (KD Pharma / AlaskOmega sourced). «Increasing from 2 to 4 capsules» is 100× more important than «switching brands».",
                zh: "大研和 Sports Research 同為 rTG 型，吸收率相當（KD Pharma / AlaskOmega 原料）。「從 2 顆增加到 4 顆」比「換品牌」重要 100 倍。" },
    },
  },

  // ===== Routine — hourly gram-precise table =====
  routineDetail: {
    hourly: {
      ttl: { en: "Hour-by-hour schedule (gram-precise)", zh: "逐小時作息（公克精確）" },
      head: { en: ["Time", "Activity", "Hydration", "Notes"],
              zh: ["時間", "活動", "補水", "備註"] },
      rows: [
        ["5:30", { en: "Wake up", zh: "起床" }, "400 mL warm water",
          { en: "Rehydrate after overnight loss", zh: "補充整夜流失水分" }],
        ["5:35", { en: "BP measurement #1", zh: "量血壓 第 1 次" }, "—",
          { en: "After bathroom, before eating. Sit 5 min, back supported, feet flat. 2 readings 1 min apart; use 2nd.",
            zh: "上完廁所、進食前。靜坐 5 分鐘背靠椅、雙腳平放。連量 2 次間隔 1 分鐘，取第 2 次。" }],
        ["6:00–7:00", { en: "Commute", zh: "通勤" }, "500 mL",
          { en: "Water bottle + 4-7-8 breathing or 10-min meditation", zh: "水壺 + 4-7-8 呼吸或 10 分鐘冥想" }],
        ["7:00–7:30", { en: "Breakfast", zh: "早餐" }, { en: "(latte / soy milk)", zh: "（拿鐵 / 豆漿）" },
          { en: "Sandwich / sweet potato combo", zh: "三明治 / 地瓜組合" }],
        ["7:30–8:00", { en: "Office — yogurt blend", zh: "辦公室 — 優格飲" }, "—",
          { en: "NO matcha. Yogurt + whey 30g + nuts + goji 15–20g + blueberries 80–100g + half banana + raw cacao 5–10g + L-citrulline 2g + D3K2",
            zh: "不放抹茶。優格 + 乳清 30g + 堅果 + 枸杞 15–20g + 藍莓 80–100g + 香蕉半根 + 生可可粉 5–10g + 瓜胺酸 2g + D3K2" }],
        ["~9:30", { en: "Hibiscus cup 1", zh: "洛神花 第 1 杯" }, "240 mL",
          { en: "Calyces 2g, steep 5–10 min. ≥1 hr from red meat / spinach / iron.",
            zh: "花萼 2g 沖泡 5–10 分鐘。距紅肉/菠菜/鐵劑 ≥1 hr。" }],
        ["11:30", { en: "Psyllium dose 1 (30 min pre-lunch)", zh: "Psyllium 第 1 劑（午餐前 30 分）" }, "240–350 mL",
          { en: "Whole psyllium husk 5g. ≥30 min from matcha latte; ≥2 hr from any other supplement.",
            zh: "全粒 5g。距抹茶拿鐵 ≥30 分；距其他補品 ≥2 小時。" }],
        ["12:00", { en: "Lunch (low-fat)", zh: "午餐（低脂）" }, { en: "Italian matcha latte 400 mL", zh: "義式抹茶拿鐵 400 mL" },
          { en: "Eggs + sweet potato + 7-11 caesar chicken salad (½ dressing). Latte = matcha 2–3g + whole milk ~300 mL. EGCG ~48–95mg. NO fat-soluble supplements.",
            zh: "蛋 + 地瓜 + 7-11 凱撒雞肉沙拉（半醬）。拿鐵 = 抹茶 2–3g + 全脂奶 300 mL。EGCG ~48–95mg。不放脂溶性補品。" }],
        ["14:00–14:30", { en: "Hibiscus cup 2", zh: "洛神花 第 2 杯" }, "240 mL",
          { en: "Reduce to 1 cup if home BP <110/70.", zh: "家中 BP <110/70 改 1 杯。" }],
        ["15:00–16:00", { en: "Afternoon snack", zh: "下午點心" }, { en: "as needed", zh: "視口渴" },
          { en: "Pumpkin seeds 30g (raw/low-roast, unsalted). Zn ~8mg + Mg ~150mg + tryptophan. NO 72% chocolate stacking.",
            zh: "南瓜籽 30g（生/低溫烘焙、無鹽）。鋅 ~8mg + 鎂 ~150mg + 色胺酸。72% 巧克力不堆疊。" }],
        ["16:30", { en: "Psyllium dose 2", zh: "Psyllium 第 2 劑" }, "240–350 mL",
          { en: "Before 17:00 cutoff. Dinner ideally ≤18:00 for 30-min gel buffer.",
            zh: "17:00 截止前。晚餐理想 ≤18:00，留 30 分鐘凝膠 buffer。" }],
        ["17:00", { en: "Hydration cutoff", zh: "補水截止" }, { en: "sips only", zh: "僅小啜" },
          { en: "Tea + psyllium stop. Plain water sips after this. Minimal soup at dinner.",
            zh: "茶 + psyllium 停。此後僅小啜白水。晚餐少喝湯。" }],
        ["18:30", { en: "Dinner (UberEats — highest-fat meal)", zh: "晚餐（UberEats — 最高脂餐）" }, { en: "sips only", zh: "僅小啜" },
          { en: "Half rice, low-Na option. After dinner: Fish oil ×4 (EPA+DHA ~2g; high-fat meal ~50% absorption boost). EGCG capsule discontinued 2026-04-21.",
            zh: "半飯、低鈉選項。晚餐後：魚油 ×4（EPA+DHA ~2g；高脂餐吸收 +50%）。EGCG 膠囊已於 2026-04-21 停用。" }],
        ["19:00–19:40", { en: "Exercise window", zh: "運動時段" }, "—",
          { en: "Wall sits / brisk walk / family activity", zh: "靠牆深蹲 / 快走 / 家庭活動" }],
        ["19:30–20:00", { en: "BP measurement #2", zh: "量血壓 第 2 次" }, "—",
          { en: "Rest 15 min after exercise before measuring", zh: "運動後休息 15 分鐘再量" }],
        ["20:00", { en: "Leg elevation 15 min + bathroom", zh: "抬腿 15 分鐘 + 上廁所" }, "—",
          { en: "Feet against wall to drain lower-limb fluid", zh: "雙腳靠牆排出下肢體液" }],
        ["20:30", { en: "Bedtime", zh: "就寢" }, "—",
          { en: "Side sleep + back pillow. Mouth tape + humidifier 50–60% RH + AC ≥26°C + saline rinse (OSA bridge). Mg glycinate 200–400mg + tart cherry 1000–2000mg + glycine 3g + chamomile.",
            zh: "側睡 + 背後枕頭。嘴封 + 加濕器 50–60% RH + 冷氣 ≥26°C + 鹽水洗鼻（OSA 橋接）。甘胺酸鎂 200–400mg + 酸櫻桃 1000–2000mg + 甘胺酸 3g + 洋甘菊。" }],
      ],
      hydrationTotal: { en: "Daily hydration total ~2.5–2.8 L (water + 2 hibiscus + matcha latte + psyllium water). At UA 8.9 target 2.8–3.0 L (≥1,920 mL/day reduces gout risk ~46%).",
                        zh: "每日總補水量 ~2.5–2.8 L（白水 + 洛神花 2 杯 + 抹茶拿鐵 + psyllium 水）。尿酸 8.9 目標 2.8–3.0 L（≥1,920 mL/日減少 ~46% 痛風風險）。" },
    },
    summary: {
      ttl: { en: "Daily supplement summary (gram-explicit)", zh: "每日補品劑量總覽（公克明列）" },
      items: {
        en: [
          "Yogurt blend: whey 30g + goji 15–20g + blueberries 80–100g + cacao 5–10g + L-citrulline 2g + D3K2 (D3 2000 IU + K2 MK-7 100mcg)",
          "Hibiscus tea: 2g × 2 cups (morning + afternoon), 240 mL each, 5–10 min steep",
          "Psyllium husk: 5g × 2 (11:30 + 16:30), each in 240–350 mL water — week 1 ramp 5g × 1, week 2+ at 5g × 2",
          "Lunch matcha latte: matcha 2–3g + whole milk 300 mL — EGCG ~48–95 mg",
          "Pumpkin seeds: 30g afternoon snack",
          "After dinner: Fish oil ×4 (EPA+DHA ~2g) — EGCG capsule discontinued",
          "Bedtime: Mg glycinate 200–400mg + tart cherry 1000–2000mg + glycine 3g + chamomile (added 2026-04-22 per Dan Go sleep tea protocol)",
        ],
        zh: [
          "優格飲：乳清 30g + 枸杞 15–20g + 藍莓 80–100g + 可可 5–10g + 瓜胺酸 2g + D3K2（D3 2000 IU + K2 MK-7 100mcg）",
          "洛神花茶：2g × 2 杯（早 + 午），各 240 mL，沖 5–10 分鐘",
          "Psyllium husk：5g × 2（11:30 + 16:30），各配 240–350 mL — 第 1 週 5g × 1 起步、第 2 週起 5g × 2",
          "午餐抹茶拿鐵：抹茶 2–3g + 全脂奶 300 mL — EGCG ~48–95 mg",
          "南瓜籽：30g 下午點心",
          "晚餐後：魚油 ×4（EPA+DHA ~2g） — EGCG 膠囊已停用",
          "睡前：甘胺酸鎂 200–400mg + 酸櫻桃 1000–2000mg + 甘胺酸 3g + 洋甘菊（2026-04-22 依 Dan Go 助眠茶協議加入）",
        ],
      },
      extras: {
        en: [
          "Post-meal walks (added 2026-04-22): 10–15 min after each meal — muscle contraction draws glucose insulin-independently, lowers HbA1c.",
          "Hourly 3-min movement break: every 60 min of work — marching / squats / push-ups at desk. Improves fasting glucose, insulin sensitivity, waist circumference.",
        ],
        zh: [
          "三餐後散步（2026-04-22 新增）：早午晚餐後各 10–15 分鐘 — 肌肉直接從血流抓糖、不需胰島素，降 HbA1c。",
          "每小時 3 分鐘運動：工作每 60 分鐘做原地踏步 / 深蹲 / 伏地挺身 — 改善空腹血糖、胰島素敏感度、腰圍。",
        ],
      },
    },
    bpTips: {
      ttl: { en: "BP measurement tips", zh: "血壓量測要點" },
      body: { en: "Recording: log date, time, SBP, DBP, HR each session in Google Sheets. Accumulate 2 weeks for clinic. Technique: sit with back against chair, feet flat (no crossing), arm supported at heart level. Sit quietly 5 min. Don't talk. 2 readings 1 min apart; use the 2nd.",
              zh: "紀錄：每次量測在 Google Sheets 記日期、時間、收縮壓、舒張壓、心率。累積 2 週帶去看診。技巧：背靠椅、雙腳平放（不交叉）、手臂支撐至心臟高度。靜坐 5 分鐘。量測中不說話。連量 2 次間隔 1 分鐘，取第 2 次。" },
    },
  },

  // ===== Safety detail =====
  safetyDetail: {
    triadPriority: {
      ttl: { en: "LVH + OSA + UA 8.9 — three-factor priority", zh: "LVH + OSA + 尿酸 8.9 — 三因子優先處置" },
      intro: { en: "These three findings interact and amplify each other. Each has a high-leverage clinical action that no supplement can replace. Order is by leverage on cardiovascular outcome.",
               zh: "這三項共病彼此放大，各自都有保健品無法取代的臨床高槓桿動作。以心血管預後槓桿排序。" },
      head: { en: ["Priority", "Action", "Why high-leverage"],
              zh: ["優先", "動作", "槓桿原因"] },
      rows: [
        ["1",
          { en: "Echo + LV mass index + 24h Holter", zh: "心臟超音波 + LV mass index + 24h Holter" },
          { en: "11-yr ECG LVH unconfirmed by imaging. Echo decides: true LVH (mass >115 g/m²) vs ECG-voltage false-positive. Sets baseline before any drug discussion. Holter screens for arrhythmia and silent ischemia.",
            zh: "11 年 ECG LVH 從未影像確診。Echo 決定：真 LVH（mass >115 g/m²）vs ECG 伏特偽陽。是任何藥物討論前的 baseline。Holter 篩心律不整 + 無症狀缺血。" }],
        ["2",
          { en: "PSG (sleep study) — POSA trial result by 5/8", zh: "PSG 多項睡眠生理檢查 — POSA 試驗 5/8 收尾" },
          { en: "T90 18.4% (severe) is independent driver of LVH + biatrial enlargement. Without fixing OSA, no BP target is sustainable; nightly desat keeps re-injuring myocardium. CPAP / MAD / surgery decision needs PSG data.",
            zh: "T90 18.4%（重度）是 LVH + 雙心房擴大的獨立驅動因子。OSA 不修，BP 怎麼降都不持久；每晚 desat 都重新打擊心肌。CPAP / MAD / 手術選擇靠 PSG 數據。" }],
        ["3",
          { en: "Cardiology consult — discuss ARB / ACEi", zh: "心臟科 — 討論 ARB / ACEi" },
          { en: "RAAS blockade is the proven LVH-regression class (LIFE trial losartan: LV mass −25 g/m² over 4.8 yr; ARB ~−13% in meta vs β-blocker −6%). Lifestyle alone cannot regress 11-yr LVH. Ideally start AFTER echo confirms (so baseline mass is documented).",
            zh: "RAAS 阻斷是 LVH regression 一線（LIFE 試驗 losartan 4.8 年降 LV mass −25 g/m²；meta ARB −13% vs β-blocker −6%）。單靠生活方式逆轉不了 11 年 LVH。理想於 echo 確診後啟動（讓 baseline mass 有紀錄）。" }],
        ["4",
          { en: "Nephrology — UA 8.9 evaluation", zh: "腎臟科 — 尿酸 8.9 評估" },
          { en: "Constitutional hyperuricemia (UA 7.8 at 26 → 8.9 at 37) won't normalize on diet/supplements alone. Persistent UA depletes NO via peroxynitrite, accelerating endothelial / cardiac damage. Febuxostat / allopurinol decision belongs to specialist. Already referred — book.",
            zh: "體質性高尿酸（26 歲 7.8 → 37 歲 8.9）不會單靠飲食 / 補品正常化。持續高尿酸透過 peroxynitrite 耗 NO，加速內皮 / 心肌損傷。Febuxostat / allopurinol 決策屬專科。已轉診，預約即可。" }],
        ["5",
          { en: "BP target reset to <125/75 (LVH-adjusted)", zh: "BP 目標重設為 <125/75（LVH 調整）" },
          { en: "General <130 is too lax for LVH patient. ESC / AHA recommend <125/80 for LVH; <120/75 ideal but watch DBP not <70 (current DBP 72 already borderline). Reset cuff target on every BP measurement.",
            zh: "一般人 <130 對 LVH 患者太寬。ESC / AHA 建議 LVH 患者 <125/80；<120/75 最理想但避免 DBP <70（目前 DBP 72 已邊緣）。每次量測對齊新目標。" }],
        ["6",
          { en: "LDL target reset to <100 (LVH + ischemia + UA = ASCVD high-risk)", zh: "LDL 目標重設為 <100（LVH + 心肌缺氧 + 尿酸 = ASCVD 高風險）" },
          { en: "Standard <130 was framed for primary prevention. Combined LVH + ECG ischemia + UA 8.9 is high-risk; LDL <100 is the appropriate target. If July recheck >130, do not delay statin discussion to month 12.",
            zh: "原 <130 是初級預防框架。LVH + ECG 心肌缺氧 + 尿酸 8.9 屬高風險；LDL <100 才是合適目標。7 月複檢若 >130，statin 討論不要拖到第 12 月。" }],
      ],
    },
    uricAcidProtocol: {
      ttl: { en: "Uric acid — additions from Taniguchi 2023 (not yet in stack)", zh: "降尿酸補充（谷口敦夫 2023 — 目前 stack 未涵蓋）" },
      intro: { en: "Source: 《尿酸（痛風）完全控制的最新療法》Taniguchi A. 2023, San-min. Items below are evidence-backed additions on top of current stack (hibiscus / tart cherry / low-purine diet). Full discussion: articles/2026-05-04-uric-acid-japanese-protocol.md.",
               zh: "來源：《尿酸（痛風）完全控制的最新療法》谷口敦夫 2023 三民。以下為現有 stack（洛神花/酸櫻桃/低普林）之外的實證補充。完整討論見 articles/2026-05-04-uric-acid-japanese-protocol.md。" },
      head: { en: ["Action", "Evidence", "Expected UA effect", "Note"],
              zh: ["動作", "實證", "預期 UA 影響", "備註"] },
      rows: [
        [{ en: "Vit C 500 mg/day at breakfast", zh: "早餐加 500 mg 維他命 C" },
          "Choi 2009 PMID: 19273781; Juraschek 2011 RCT meta",
          { en: "−0.3 to −0.5 mg/dL in 4 wk", zh: "4 週 −0.3 至 −0.5 mg/dL" },
          { en: "Promotes URAT1 inhibition → renal UA excretion. NT$5–10/cap.", zh: "抑制 URAT1 → 腎臟尿酸排泄。NT$5-10/顆。" }],
        [{ en: "Coffee 2–3 cups/day (no sugar, before 14:00)", zh: "無糖咖啡 2-3 杯/日（14:00 前）" },
          "Choi & Curhan 2007 PMID: 17530645",
          { en: "Gout risk ↓ 40–57% long-term", zh: "痛風風險 ↓ 40-57%（長期）" },
          { en: "Chlorogenic acid → XO inhibition + insulin sensitivity. Existing breakfast latte counts.", zh: "綠原酸 → XO 抑制 + 改善胰島素敏感度。現早餐拿鐵已算 1 杯。" }],
        [{ en: "≥2 servings low-fat dairy/day", zh: "每日 ≥2 份低脂乳製品" },
          "Choi 2004 NEJM PMID: 15014182",
          { en: "Gout risk ↓ 43%", zh: "痛風風險 ↓ 43%" },
          { en: "Casein + whey are uricosuric. Whole-fat milk shows NO effect — switch lunch latte to low-fat.", zh: "酪蛋白 + 乳清促排泄。全脂無效 — 午餐拿鐵改低脂奶。" }],
        [{ en: "Daily purine target ≤ 400 mg", zh: "每日普林 ≤ 400 mg" },
          { en: "JCGS 2022 guideline 3rd ed", zh: "日本痛風學會 2022 指引第 3 版" },
          { en: "Hard ceiling — log 1 week to verify", zh: "硬上限 — 記錄 1 週確認 baseline" },
          { en: "Liver/kidney/anchovy/sardine = avoid (>300 mg/100g); chicken/fish moderate; eggs/tofu/dairy/vegetables free.", zh: "肝/腎/鯷魚/沙丁魚（>300 mg/100g）避；雞魚適量；蛋/豆腐/乳製品/蔬果安心。" }],
        [{ en: "Urine output 2 L/day target (separate from intake)", zh: "尿量 2 L/日目標（與飲水量分開）" },
          { en: "JCGS guideline", zh: "JCGS 指引" },
          { en: "Maintains renal UA clearance", zh: "維持腎臟尿酸清除率" },
          { en: "Requires water intake 2.5–3 L (already done). Self-check: pale-yellow urine + ≥5 voids/day.", zh: "需飲水 2.5-3 L（已做）。自檢：尿色淡黃 + 每日 ≥5 次排尿。" }],
        [{ en: "Weight loss pace 0.5–1 kg/month", zh: "減重速度 0.5-1 kg/月" },
          "Dessein 2000 PMID: 10977967",
          { en: "−0.1 to −0.3 mg/dL per kg lost", zh: "每 kg ↓ 0.1-0.3 mg/dL" },
          { en: ">1.5 kg/wk → ketone competition raises UA acutely. Current 0.83 kg/mo plan ✓ aligned.", zh: ">1.5 kg/週 → 酮體競爭排泄反升 UA。現計畫 0.83 kg/月 ✓ 對齊。" }],
        [{ en: "Alcohol-free days ≥1–2/week (when drinking resumes)", zh: "若恢復飲酒：每週 ≥1-2 休肝日" },
          { en: "JCGS guideline", zh: "JCGS 指引" },
          { en: "Currently abstinent — already exceeds", zh: "目前完全戒酒 — 已超標達成" },
          { en: "Beer worst (purines + ethanol). Whisky 60 mL or wine 120 mL is per-day cap if drinking.", zh: "啤酒最差（普林 + 酒精雙打擊）。若喝：威士忌 60 mL 或紅酒 120 mL 為日上限。" }],
      ],
      ceiling: {
        en: "Lifestyle ceiling for constitutional hyperuricemia is ~UA 8.0. Below that requires xanthine oxidase inhibitor (febuxostat / allopurinol) — nephrology consult is the path. These additions buy −0.5 to −1 mg/dL on top of existing stack and reduce gout-flare risk meaningfully, but won't substitute for drug therapy at UA 8.9 baseline.",
        zh: "體質性高尿酸的生活方式天花板約 UA 8.0。低於此需 XO 抑制劑（febuxostat / allopurinol） — 腎臟科是正解。以上補充在現 stack 之上額外降 0.5-1 mg/dL、有意義降痛風發作風險，但無法取代 UA 8.9 baseline 的藥物治療。",
      },
    },
    liver: {
      ttl: { en: "Fatty liver & GOT/GPT — what the numbers mean", zh: "脂肪肝與 GOT/GPT — 數字解讀" },
      body: { en: "Visceral fat drives hepatic steatosis via fructose → VLDL pathway. Fatty liver is silent until GOT/GPT elevate. Goji 45-day RCT improved GOT/GPT in metabolic syndrome [PMC5480053]. Include GOT, GPT, GGT in Month 0 baseline bloodwork.",
              zh: "內臟脂肪透過果糖 → VLDL 路徑驅動肝脂肪變性。脂肪肝在 GOT/GPT 升高前無症狀。枸杞 45 日 RCT 改善代謝症候群患者 GOT/GPT [PMC5480053]。第 0 月基準抽血含 GOT、GPT、GGT。" },
      head: { en: ["Marker", "Month 0", "Month 3", "Month 6"],
              zh: ["指標", "第 0 月", "第 3 月", "第 6 月"] },
      rows: [
        ["GOT (AST)", { en: "Baseline", zh: "基準" }, { en: "Trending down", zh: "下降中" }, "< 40 U/L"],
        ["GPT (ALT)", { en: "Baseline", zh: "基準" }, { en: "Trending down", zh: "下降中" }, "< 40 U/L"],
        ["GGT", { en: "Baseline", zh: "基準" }, { en: "Trending down", zh: "下降中" }, { en: "Normal range", zh: "正常範圍" }],
        [{ en: "Triglycerides", zh: "三酸甘油酯" }, { en: "Baseline", zh: "基準" }, "↓ 15–30%", "< 150 mg/dL"],
        [{ en: "Uric acid", zh: "尿酸" }, { en: "Baseline", zh: "基準" }, "↓ 10–20%", "< 6.0 mg/dL"],
      ],
    },
    medicalVisits: {
      ttl: { en: "Medical visit plan", zh: "就醫計畫" },
      head: { en: ["Purpose", "Where", "When"], zh: ["目的", "地點", "時間"] },
      rows: [
        [{ en: "Sleep clinic (OSA / PSG)", zh: "睡眠門診（OSA / PSG）" }, { en: "Hospital with sleep center", zh: "有睡眠中心的醫院" }, { en: "Book this week", zh: "本週預約" }],
        [{ en: "Urology (nocturia)", zh: "泌尿科（夜尿評估）" }, { en: "Same hospital or nearby clinic", zh: "同醫院或附近診所" }, { en: "Same day if possible", zh: "盡量同天" }],
        [{ en: "Baseline bloodwork", zh: "基準抽血" }, { en: "Any medical facility", zh: "任何醫療機構" }, "Month 0"],
        [{ en: "3-month follow-up", zh: "3 月追蹤" }, { en: "Same facility", zh: "同一機構" }, "Month 3"],
        [{ en: "6-month comprehensive recheck", zh: "6 月全面複檢" }, { en: "Same facility", zh: "同一機構" }, "Month 6"],
        [{ en: "Nephrology referral (UA 8.9)", zh: "腎臟科轉診（尿酸 8.9）" }, { en: "Specialist clinic", zh: "專科門診" }, { en: "Pending", zh: "已轉診" }],
      ],
    },
    warningSigns: {
      immediate: {
        ttl: { en: "Seek immediate medical attention", zh: "立即就醫" },
        items: {
          en: [
            "BP > 180/120 mmHg — hypertensive emergency.",
            "Chest pain, tightness, or pressure — cardiac concern.",
            "Sudden severe headache with visual disturbance — possible stroke.",
            "One-sided limb numbness or weakness — possible stroke.",
          ],
          zh: [
            "血壓 > 180/120 mmHg — 高血壓急症。",
            "胸痛、胸悶或壓迫感 — 心臟疑慮。",
            "突發劇烈頭痛伴隨視覺異常 — 可能中風。",
            "單側肢體麻木或無力 — 可能中風。",
          ],
        },
      },
      soon: {
        ttl: { en: "See a doctor within 1–2 days", zh: "1–2 天內就醫" },
        items: {
          en: [
            "Sudden severe joint pain with redness/swelling — possible acute gout. Rapid weight loss or dehydration can trigger it.",
            "Persistent dizziness or blurred vision — BP may be dropping too fast or blood sugar too low.",
            "Chest tightness or palpitations during exercise — intensity may exceed safe range.",
            "Urine consistently dark yellow / brown — insufficient hydration or kidney concern.",
            "Weight drops > 1.5 kg in one week — too fast. Raises UA, gout/gallstone risk.",
            "Prolonged loss of appetite or depressed mood — caloric restriction may be too aggressive.",
            "Home BP persistently > 160/100 — needs medical evaluation.",
          ],
          zh: [
            "突發嚴重關節疼痛伴紅腫 — 可能急性痛風。急速減重或脫水可能誘發。",
            "持續頭暈或視力模糊 — 血壓可能降太快或血糖過低。",
            "運動中胸悶或心悸 — 強度可能超過安全範圍。",
            "尿液持續深黃 / 褐色 — 水分不足或腎功能疑慮。",
            "一週體重掉 > 1.5 kg — 太快。升高尿酸、增加痛風 / 膽結石風險。",
            "持續食慾不振或情緒低落 — 熱量限制可能太激進。",
            "居家血壓持續 > 160/100 — 需醫療評估。",
          ],
        },
      },
    },
    exerciseSafety: {
      wallSit: {
        ttl: { en: "Wall sit safety", zh: "靠牆深蹲安全" },
        body: { en: "NEVER hold your breath — most important rule. Breath-holding spikes BP, defeating purpose. Stop immediately if dizzy / chest tight / sharp knee pain. Consult doctor first if cardiovascular disease.",
                zh: "絕對不要憋氣 — 最重要規則。憋氣使血壓瞬間飆升，完全失去降壓目的。頭暈 / 胸悶 / 膝蓋劇痛立即停。心血管疾病者先諮詢醫師。" },
      },
      ua: {
        ttl: { en: "Exercise with elevated UA", zh: "尿酸偏高的運動注意" },
        body: { en: "Avoid high-intensity vigorous exercise (lactic acid blocks UA excretion). Stick to RPE 4–6/10. Hydrate before & during. Never exercise on empty stomach (ketones raise UA).",
                zh: "避免高強度劇烈運動（乳酸抑制尿酸排泄）。維持 RPE 4–6/10。運動前與中都補水。絕不空腹運動（酮體升高尿酸）。" },
      },
    },
  },

  // ===== OSA POSA Trial (5/5–5/8) =====
  osa: {
    intro: {
      en: "SpO2 desaturation events have been escalating: T90 ≥ 10% on 4/29, 4/30, and 5/4 (peak 18.4% — severe). 5/4 attributed to dual stack: high-sodium meal 36–40 h prior + 2-night REM debt rebound. Positional therapy (POSA) trial runs 5/5–5/8 in parallel with PSG booking.",
      zh: "SpO2 desat 事件持續升級：4/29、4/30、5/4 T90 ≥ 10%（高峰 18.4% — 重度）。5/4 歸因於雙因子疊加：36–40h 前高鈉餐 + 連兩晚 REM 負債反彈。體位治療試驗（POSA）5/5–5/8 與 PSG 預約並行。",
    },
    intervention: {
      ttl: { en: "Level-1 intervention", zh: "Level 1 介入" },
      items: {
        en: [
          "Head of bed elevated 20–30° (pillow / towel roll).",
          "Body pillow in front, firm pillow behind back to block supine.",
          "If supine return < 5 min → upgrade to tennis-ball shirt.",
        ],
        zh: [
          "床頭抬高 20–30°（疊枕 / 毛巾捲）。",
          "身前抱長抱枕，背後放扎實小枕頭擋翻仰。",
          "若 5 分鐘內翻仰 → 升級網球療法。",
        ],
      },
    },
    readout: {
      ttl: { en: "Decision criteria — averaged over 4 nights", zh: "判讀準則 — 4 晚平均" },
      rows: [
        ["≤ 5%", { en: "Strong POSA — upgrade to SPT vibration device", zh: "強烈 POSA 反應 — 升級 SPT 震動裝置" }, "ok"],
        ["5–10%", { en: "Moderate — reinforce elevation / tennis-ball", zh: "中度 — 加強床頭抬高 / 網球" }, "warn"],
        ["> 10%", { en: "Not POSA-driven — PSG → CPAP/MAD", zh: "非 POSA 主導 — PSG → CPAP/MAD" }, "bad"],
      ],
    },
  },
};
